apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: local-path-provisioner
      version: 0.0.35
      sourceRef:
        kind: HelmRepository
        name: containeroo
        namespace: flux-system
  install:
    createNamespace: false
  values:
    storageClass:
      defaultClass: true
    nodePathMap:
      - node: "k8s-homelab"
        paths:
          - "/mnt/k8s"
      - node: "DEFAULT_PATH_FOR_NON_LISTED_NODES"
        paths:
          - "/mnt/k8s"
