apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    admin-username: ENC[AES256_GCM,data:8Hjpjyw=,iv:poQJde8rLDw/UQs4H8nkqil8k5S/P371LtqWfM2M6zc=,tag:G6AlvTJ83vXNiQGh9hav5g==,type:str]
    admin-password: ENC[AES256_GCM,data:Amw2UHHDELnLFzKyIZVMN63uQ9cY2sHSghFKNDuPv5F5JP2TTYiwIPcgo/naXaoWYmOdmkC2I4mEdlZ0sd2Vsw==,iv:nVLZpenEq60Ev4fnocMkJVoa/trBqUc4zCRCtwHoGd4=,tag:ncsNvoZySNH/HaDdgbvARQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:DDC43vYrrVxhc5HSsewkveN50zRpzLte5zohA3atpWH6QoSl6u1Jbg==,iv:13HOR7N1i1Qwzy9etBgiwG/xwHPjJIPIJpGonQCuMLc=,tag:38ku6Y1/WKJnVPLfP7NtCQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:PQs0exvi9ismNxPzhDftfyPxbnp3siatA/DCeG8TZ8tZ1ggqaxFwOm35b7zK/7VFlB0I6zbwzkne2YqEPTlh1JVQNVvh82GywxWcCHHwpQCkoSqMQHAhf6UaDtl5z7qAcC2Xu4ftEdB5EfMjqmdqVfNSLxutbUbzHbQeuj3VZbU=,iv:iMXrPNECaj0AeS69GsQuT2jXQUXa4Zs/Mrk93sxfbVw=,tag:fK/LRJLvvU5fqCZEkAWQIg==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZEl2dVh5U1VVb1BQUmhl
            bSsyd3dFRUF0VlQ0bTIwMHMyZ3NHdHhxVEQwCmZuaVcwSTB1U084VVQ4a1FvdkNk
            YVNGUlErSGFpRWxwNmE3UFJEY293N3MKLS0tIFY4MU4rZEJGSWdDY1AyQ0VzVEtZ
            cERTemVBV2c4TmtaSlZKTytjYXFmU0kK2zBw8wKE9acaNcUoNidIv0Fu7RO1uG7b
            MEb+G0pxJvarPNrc4I2NuI7zykIbUUZUboBtav7UpFQl6ZKs0DEYbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:57:40Z"
    mac: ENC[AES256_GCM,data:PqOFmhFBpSsCxSX+JKfGStxJgNKBNYHKrUHW2bww+nNxaoiLJDzvnRX6QCPINcHa9Bx/IjcjaqQ2DGLvBSLYBQzD7WSgUKb4w0w0AlC7MZDi7XiHIETkETFd71pUT5clqSTuTocfFDKkssKuIDLlQH8cUTWsExdnwRM+5488sr8=,iv:0vRTOjV4JzFFvZPXcoyqPH9+5aTWdyMyjDU3Ej98rNo=,tag:Gt3YePU0tRTKT8w3F0gAFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
