# TODO: encrypt before use: sops --encrypt --in-place secrets/nextcloud/nextcloud-admin.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
type: Opaque
stringData:
  admin-username: admin
  admin-password: CHANGEME
  OIDC_CLIENT_ID: CHANGEME
  OIDC_CLIENT_SECRET: CHANGEME
