# TODO: encrypt before use: sops --encrypt --in-place secrets/nextcloud/rustfs-credentials.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: nextcloud
type: Opaque
stringData:
  RUSTFS_ACCESS_KEY: CHANGEME
  RUSTFS_SECRET_KEY: CHANGEME
