apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: nextcloud
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:t5xdKTs4U+tu,iv:6SUGprgWrWcBaaqzpM07LbuWDWOf4INWZcULl73JPJs=,tag:3vKnYYEOGBOzc+WHMvPYVg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:cJ+oASGKPY+7PA9JGXy8fw29ROHUSTdjDB9w8FK/qoDz/4Kou3z+Z7Vdt3yyGGdARZDj+R8XUhf9IQiC+z+AeA==,iv:JgSCoHKA0FJ06GsykNA1IUmqt+/tYpv+1Vqh2eFTPZI=,tag:hZu+rYLJ+aiavCX999Sd0g==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWDlIUmIzZWhXTmFzUWVz
            djFyWkFLei9tdFp1cUY1MlE1eU5mWU5Vd1ZvCnRCVDlkaFB5MHZOUDhPek1TTFNa
            RmlCaDlIL3Y1eUZHQUVyMExRYjR2ZFkKLS0tIHRjYlpycE44TWZiaFRYb2NuNVZo
            UWg4R3pNdm9IR3RMQTdYdjE0VVZFVnMKHrWnv8SXio1BR5/JSF0eQhtkspAU3/dk
            LNnF3+A4bwfQmBQEvHAanwulNelJfghktGoSb2BJO9vwGHLP2CJwYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T15:57:32Z"
    mac: ENC[AES256_GCM,data:f1HCcW2CJw8wE4Ge3Bt/equ7QORcor5vtQGhQrv86YDMGjCQU9SD6XnYOLGZBTA8LIapesGfr0+a4Qv8REiQIzJYuhrDo5GhgQCvkBVG1W7DpYTSZt6ns5/rApVdQq1hkdTnJBlv+7vYNsGUBJYO8Fg/VxVhJ/1xt16A5amGgQI=,iv:TDRb1n62uTHB1FRLrIwxJGguGh9Qy9KPtUMIg/HDXmE=,tag:rhHTs6kQH4F3lIlGJCnHfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
