stages:
  - maintenance

variables:
  GIT_STRATEGY: fetch

helm_chart_bump:
  stage: maintenance
  image: alpine:3.20
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - when: manual
  before_script:
    - apk add --no-cache bash git curl tar yq
    # Install crane (static binary)
    - |
      CRANE_VER=v0.20.6
      ARCH=x86_64
      URL="https://github.com/google/go-containerregistry/releases/download/${CRANE_VER}/go-containerregistry_Linux_${ARCH}.tar.gz"
      echo "Downloading crane from ${URL}"
      curl -sSL -o /tmp/crane.tgz "$URL"
      tar -C /usr/local/bin -xzf /tmp/crane.tgz crane
      chmod +x /usr/local/bin/crane
      crane version || true
    # Configure git to push with CI job token
    - git config user.name "helm-bump-bot"
    - git config user.email "helm-bump-bot@example.com"
    - git remote set-url origin "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  script:
    - bash scripts/update_helm_charts.sh
