creation_rules:
  - path_regex: secrets/.*\.(ya?ml)$
    encrypted_regex: '^(data|stringData)$'
    age: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
  - path_regex: .*\.enc\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
