creation_rules:
  - path_regex: secrets/.*\.(ya?ml)$
    encrypted_regex: '^(data|stringData)$'
    age: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
  - path_regex: .*\.enc\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
