apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-openvpn
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:Y8Vm+bpoHdbakq9VM4lvsv+f42s=,iv:MzX51ys4Z3lbFpDvziZW8L7uARkZANNHQc3xSVVXsAA=,tag:IQnF1ZBlv379K0p9I4R4pQ==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:BEbnJ3uQj+l3yfevbKh0fnpi0/vluPV1Jxu31qyEqYw=,iv:JbLfgRiE+94AnI8AbrGXrzdLkHp36rmNjEKYOIC24ao=,tag:9QZkQXh6t5WvSJSgnAdOoQ==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dW03R1MzMEFZU1ZLdDJm
            dHNrR2VMR3laSUdrRk4wMGNvYmlCT296OFhRClI5a29nbTl1di9nb0VqQTJ0bXZ6
            TmMycWg1NC9lK3VOQTBIS20yTzIvNXMKLS0tIDdaSHFhem9EVjV1MHplSTRZY1Ru
            WjRkNWorOGNSckdBbnoxWlNTcDF2VjAK4KK4pBinQOmDf0PCl4e/tPefPtp3f/hw
            snHO124zSehKPUnuydC+dFCrluqqRvZGwVm1NDkVxbiM33nKi5RFeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:23:50Z"
    mac: ENC[AES256_GCM,data:VQcXv3XVs1Dye8UCd0g84SJi1uMYtL0hJzCp3kbydOFInjmxGJlvTebowAsw9ZvstxBRo2ffbL2Rk+nFKLGwuNNJmUNAcurjdcFzYUFKonbMTGnmZiM9yr/zY47mNtjJntOsKp49kydGsgMQmf4Cy0bP5MZ2tzE5hCP4wfpE1Lk=,iv:UmPb6Phw2+oGZv+LZRqflLCLF5+QWNvFKUEAb+RTq10=,tag:MD0F0m02xiZocjFDFqZM8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
