apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: scolx-postgres-cluster
  namespace: scolx
spec:
  instances: 1
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-superuser-secret
  storage:
    size: 10Gi
