apiVersion: apps/v1
kind: Deployment
metadata:
  name: scolx-server
  namespace: scolx
  labels:
    app: scolx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scolx-server
  template:
    metadata:
      labels:
        app: scolx-server
    spec:
      imagePullSecrets:
        - name: scolx-registry
      containers:
        - name: scolx-server
          image: registry.cherkaoui.ch/scolx/scolx-v2/server:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scolx-postgres-cluster-app
                  key: fqdn-uri
          envFrom:
            - configMapRef:
                name: scolx-server-config
            - secretRef:
                name: scolx-server-env
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /startupz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
