apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: scolx
spec:
  interval: 10m
  chart:
    spec:
      chart: pgadmin
      version: '[helm-bump] crane ls tccr.io/truecharts/pgadmin'
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    service:
      main:
        type: ClusterIP
