apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: scolx
spec:
  interval: 10m
  chart:
    spec:
      chart: pgadmin
      version: 19.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    service:
      main:
        type: ClusterIP
