apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: scolx
spec:
  interval: 10m
  chart:
    spec:
      chart: minio
      version: "5.4.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: false
  values:
    mode: standalone
    replicas: 1
    drivesPerNode: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Ti
    existingSecret: minio-root-credentials
    service:
      type: ClusterIP
      port: "9000"
    consoleService:
      type: ClusterIP
      port: "9001"
    ingress:
      enabled: false
    consoleIngress:
      enabled: false
    buckets:
      - name: uploads
        policy: none
        purge: false
        versioning: true
