apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scolx
resources:
  - namespace.yaml
  - deploy-server.yaml
  - svc-server.yaml
  - ingress-server.yaml
  - configmap-server.yaml
  - middleware-internal-only.yaml
  - cnpg-cluster.yaml
  - helmrelease-pgadmin.yaml
  - cronjob-reminders.yaml
  - cronjob-rt-cleanup.yaml
  - cronjob-stripe-cleanup.yaml
  - cronjob-email-verification-cleanup.yaml
  - servicemonitor.yaml
  - helmrelease-rustfs.yaml
  - svc-mathapi.yaml
  - deploy-mathapi.yaml
  - ingress-rustfs.yaml
