apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw-operator
  namespace: openclaw
spec:
  interval: 10m
  chart:
    spec:
      chart: openclaw-operator
      version: "0.9.22"
      sourceRef:
        kind: HelmRepository
        name: openclaw
        namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    crds:
      install: true
      keep: true
