apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: openclaw
spec:
  autoUpdate:
    enabled: true
    checkInterval: "24h"
    backupBeforeUpdate: true
    rollbackOnFailure: true
    healthCheckTimeout: "10m"
  runtimeDeps:
    pnpm: true
    python: true
  initContainers:
    - name: install-kimi-claw
      image: nikolaik/python-nodejs:python3.12-nodejs22
      command:
        - sh
        - -c
        - |
          set -e
          mkdir -p /extensions/kimi-claw
          curl -fsSL https://cdn.kimi.com/kimi-claw/kimi-claw-latest.tgz -o /tmp/kimi-claw.tgz
          tar -xzf /tmp/kimi-claw.tgz -C /extensions/kimi-claw --strip-components=1
          rm /tmp/kimi-claw.tgz
          cd /extensions/kimi-claw
          npm install --omit=dev
          chmod -R 755 /extensions/kimi-claw
          echo "Kimi Claw plugin installed successfully"
      volumeMounts:
        - name: extensions
          mountPath: /extensions
  extraVolumes:
    - name: extensions
      emptyDir: {}
  extraVolumeMounts:
    - name: extensions
      mountPath: /home/openclaw/.openclaw/extensions
  config:
    raw:
      plugins:
        load:
          paths:
            - /home/openclaw/.openclaw/extensions/kimi-claw
        entries:
          kimi-claw:
            enabled: true
            config:
              bridge:
                token: "${KIMI_CLAW_TOKEN}"
                promptTimeoutMs: 1800000
              gateway:
                url: "ws://localhost:18789"
      agents:
        defaults:
          model:
            primary: "kimi-coding/k2p5"
      session:
        scope: "per-sender"
      gateway:
        bind: lan
  envFrom:
    - secretRef:
        name: openclaw-secrets
  storage:
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
  chromium:
    enabled: true
  selfConfigure:
    enabled: true
    allowedActions: [skills, config, envVars, workspaceFiles]
