apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: jellyfin
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  install:
    createNamespace: false
  values:
    persistence:
      config:
        enabled: true
        size: 5Gi
      media:
        enabled: true
        existingClaim: plex-media
        mountPath: /media
    metrics:
      enabled: true
