apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: plex
      version: 20.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    persistence:
      config:
        enabled: true
        size: 5Gi
      media:
        enabled: true
        existingClaim: plex-media
        mountPath: /media
    plex:
      additionalAdvertiseURL: "https://plex.cherkaoui.ch"
