apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: qbittorrent
      version: 24.2.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    podOptions:
      dnsPolicy: None
      dnsConfig:
        nameservers: ["1.1.1.1"]
        searches: ["media.svc.cluster.local", "svc.cluster.local", "cluster.local"]
        options:
          - name: ndots
            value: "1"
    persistence:
      config:
        enabled: true
        size: 2Gi
      movies-shows:
        enabled: true
        existingClaim: qbit-media
        mountPath: /movies-shows
        subPath: movies-shows
    addons:
      gluetun:
        enabled: true
        type: gluetun
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.40.0
        killSwitch: true
        excludedNetworks_IPv4: ["192.168.1.0/24"]
        excludedNetworks_IPv6: []
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        container:
          env:
            FIREWALL: "on"
            DNS_ADDRESS: "1.1.1.1"
            FIREWALL_OUTBOUND_SUBNETS: "1.1.1.1/32,172.16.0.0/16,172.17.0.0/16,192.168.1.0/24,104.16.132.229/32,10.2.0.0/16"
            DNS_KEEP_NAMESERVER: "off"
            VPN_TYPE: "openvpn"
            VPN_SERVICE_PROVIDER: "protonvpn"
            VPN_PORT_FORWARDING: "on"
            FIREWALL_VPN_INPUT_PORTS: "59241"
  valuesFrom:
    - kind: Secret
      name: qbittorrent-openvpn
      valuesKey: OPENVPN_USER
      targetPath: addons.gluetun.container.env.OPENVPN_USER
    - kind: Secret
      name: qbittorrent-openvpn
      valuesKey: OPENVPN_PASSWORD
      targetPath: addons.gluetun.container.env.OPENVPN_PASSWORD
    - kind: Secret
      name: qbittorrent-openvpn
      valuesKey: openvpn.conf
      targetPath: addons.gluetun.container.env.OPENVPN_CONFIG
