apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: radarr
      version: 26.3.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    persistence:
      config:
        enabled: true
        size: 2Gi
      movies:
        enabled: true
        existingClaim: plex-media
        mountPath: /movies
        subPath: movies
      qbitmovies:
        enabled: true
        existingClaim: qbit-media
        mountPath: /movies-shows
        subPath: movies-shows
