apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notifiarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: notifiarr
      version: 7.12.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    persistence:
      config:
        enabled: true
        size: 2Gi
  valuesFrom:
    - kind: Secret
      name: notifiarr-env
      valuesKey: NOTIFIARR_APIKEY
      targetPath: notifiarr.apikey
