apiVersion: v1
kind: Secret
metadata:
    name: lockbox-config
    namespace: lockbox-system
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:4H+NV+GkpDdAsqnBVl07GYO+l6cgm1OlAT94WOeJMsLwrY+RypogM/03UyeN63TvmQAmFQ==,iv:ZiikrPAm4xp5b4F63Fapa51TNTANbh2UZKCsR//421Q=,tag:NX4imxbvG484VlXEJaYpeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eXg0S2N6QUNXcGw1QVR5
            dEM2MzBNZ3ZlTWE5THRUZitOOVA2ZGYwQ0IwClZCV05lblQ5SktsL1A5M3BiNWM5
            am1WTjN0QVBzSTBFUGhCeTU5UXNBUWsKLS0tIFUwbTRtbEo2d1UySmd3NThUSWx1
            bEdkM2g5UnE2Q2hvcWpUN2IxbWw5Q1UK+xrpnoheuYJAHFY5US9A7QupRnFyxOED
            jGdtydzb3oMuVbNPRFQ+Rp7gwfcRgrsLjbkj8nsR+M4Db/aiA+kF5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T17:07:30Z"
    mac: ENC[AES256_GCM,data:SocBAkBfuIUoZX/sHhW8M/Uj1DJeWoV4JnMTPakoMKCKSaFtbfO6ApqUoUeb+53VKXqecj449hwU8Np492/sAtdcJIafZdcdxloooIxczfqs3kwVAi5jsLzMneDFyvKl7L3/BhE+pg2taaUqC5brPWUQfu0E68SYXrCuq6RiD6A=,iv:1V4w6v923rD8AOaJdhRqo6epaq0ha8H9jLao5SHfPP0=,tag:dsSUHUJLfbOybHgk63YunA==,type:str]
    version: 3.13.1
