apiVersion: v1
kind: Secret
metadata:
    name: lockbox-credentials
    namespace: lockbox-system
type: Opaque
data:
    seed: ENC[AES256_GCM,data:SvbN3FN6NG3lgkGKbjjYARp4KmhWo0S5ttKfdPdsxWDAkORfnr4BxVD3I7A=,iv:3AxW8YYpH2lELY4tZJOfyZHdr3LdJMdFp/Zb8l746no=,tag:NerOy1TzS9n5aZ4+gfqE0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZmZTWlpUV1QyclFaT0Zn
            emVVNlVUNkhCbmtKSzBVSFZTa2cxdlpYN0FNCnpONllGT2o2WGpNUHI3bU10VGg2
            dkFTTUhXNklmUmYzTUZKVTZ2eUFLVlkKLS0tIDJFK0hkT0lXdUhIRzNWU0xtdzRI
            RTAzWHVRdVVVUVNWMkQ2Z1FGVm00Q3MKkDsPjanvkjV+8j28dg7KsC99N/rCXSdq
            iu8Idae+2MQvA2UxZLJbzAkU3OLITxV9JaU68yYB9SaB1JxrsDKNQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T11:48:16Z"
    mac: ENC[AES256_GCM,data:YXddXXSJhlh9zUE3OnxjD61s/hz4Kx/lie6CU2Fc7SkNBe5ueJi2QwOMZ0K0vZvB5N20RaZqu9g7+K+OH2rivDv/sHYSXt9MJCai1xKxyndn9LHcMPiKiV9vg/5UMMclmA5LywyVXFDpCKE3XC+gFre8+EBHk1cesf4ZxVSidYg=,iv:z6hlqgBCuO4ZXQ25CbLAknSDIiQ1uKKkP3P5WU2QzTQ=,tag:KV9130VRCs1FHA98g102pg==,type:str]
    version: 3.13.1
