apiVersion: v1
kind: Secret
metadata:
    name: lockbox-credentials
    namespace: lockbox-system
type: Opaque
data:
    seed: ENC[AES256_GCM,data:HDsk1IkgAQ3b5gc+ICVfg0h9PB+zpeJJytWnKCpbZ4ynv5zYK1FIDFx3Aqw=,iv:XMfcGEbMDIj3ASq3iNQWOFeH5K2kYx5KqSefiYVna6s=,tag:FtSmTLf2WAfWHB9RS7vwOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV05XanJJVlZzZEUvLy9J
            Um53elljYTlmdnNGS1hrZlp3dnNQM01nT3lJCmJmM045K0tKZGNTUGtLMHpUOXZT
            SkQybmRUK0FCNU1Ga0ErOTVNQXhFUWcKLS0tIGRqYTJpVFk3cnJBSUszSm9YcDNE
            NTBVQituUms2NVhMSHF3UXM0RmpUTDAKY6I5LsUNqKeQptvrbPLXdT7xBUQHYYHb
            7+U6urQ/7xGyfmrVOYoCPky7+8KeLXBealvccn7qoihWLyrTBU7V+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:31:04Z"
    mac: ENC[AES256_GCM,data:/53382bfBOsmEre+o7HwAdxvbG8vLyr1YZiTrq4Cb7cQ3VNZy0z/chyZP97KMpblq0NzXOV0+7RxNYHMnxeT2c5TT0NP49gB7PTe75HRQYJRk+g9BuITLmz5d+I3qA8G44SqNmYcqvDDq2MiinuqkcMzcfn95r9myCmQTn2copU=,iv:t0zdS8OTAfpR+FZbEAPUpbfachehyMNCCziJ9d5F7zI=,tag:mAQfHL/hf1j8ZBQQES4GDQ==,type:str]
    version: 3.13.1
