apiVersion: v1
kind: Secret
metadata:
    name: lockbox-credentials
    namespace: lockbox-system
type: Opaque
data:
    seed: ENC[AES256_GCM,data:x0n/90a3CXe21lWuOJWEZgzzasKGsHjbM12cp6bU8bb31UDHXv/3rSQRjws=,iv:JFj1oY4MFkJjEi3GtsUPyip2KzIWkLdx3AuNHTxVBlo=,tag:46WVsJBEfGJavy+9coQfFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTldXVy81STBrclNXVWc5
            YzZrTEovc1hBTWV3TXJTM1dOOS9nTDRSbW40Cll5bFZZWDdXTUhvUlc0b2V4eEtr
            cnd6QTduUmpvYTJtaSt1WWY2SHcvc1EKLS0tIGhVZGgweDkxTW8yckwvSk9YZjhK
            bFRXOXNHaExaMzBEUXdrbEJQZUN3UHcKtpjmYTxfwarRkgxwjpONovGNYMUrqSbG
            oMciPEOMx5aICyCgMrfzmlVyDKtxwPuOBBwVJHVFTJTxbgaHOJq4pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T17:07:30Z"
    mac: ENC[AES256_GCM,data:WpWr2S7vRMbsEOFYoFVmNiBRFgw/vlqGlAm9bUAPKSfd8n6lY7MbMcsQfxLLguTxVUZNT+yZh2QGRFSCz0Dx8i/NljNUFhKd4rOP386SH+yAtf0tlnHknuTZy5grI3Rkt3RA30WOGcZA3vHQSYFUc+cBy0RqVQ+CBInFxPwBn1Q=,iv:vqRlxlFofI67Exa7z+GttiV/3MsfVqVEpH2/7SH9lS8=,tag:cfzAkZNlQfVAakDI5GRO4A==,type:str]
    version: 3.13.1
