apiVersion: v1
kind: Secret
metadata:
    name: lockbox-config
    namespace: lockbox-system
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:T6isU+khFIDjK9qk7ZViNEAAFL2H9uMN/vJtYw==,iv:HWiVF/FCkOQj7XMWoJOM0OJsvZTrLTVyTmUQsYNGTLc=,tag:cbP8WtgbLkM3lwKbWJAYWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSFpaYTZrVkRmVkE0b3Zn
            d3p4U1hyaC9KMWFSWFdEVkxaWEZHTTFVWWdjClR2UVh0WWhNN0VhSFBGOFRNM0U3
            K3djRjgrUEV4aFJySHB0TWVhSDRWWjQKLS0tIDBxY0toVEZMTVhjRUFIcCtEWXA1
            MXBBcThzRlR2aVM1aFVoKzRWNlZXYjAKvwq9IpHKc6goFG1tfWg6DWPOdAqseuPj
            tOo4Ax5W9J5SytlGR3G65SLBtZH5MaEZpsjgRlBCvks3AC8LOx0XEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T11:33:32Z"
    mac: ENC[AES256_GCM,data:rjZFs9Vk+ltVix1vPLEubK6CZG+BFWT52TQQa/eCC0FwyWtJwj1cKiKffN0yCm3erJjNFlGV8dTHz1xWg/eizxdkj3E/RPHaCiPxpbD7PKhP75yezN4r6mB5OTjC58mhMepo3xpIeEkyCelqIghw/rIwB+Wm29QMMS5HFPN6pyo=,iv:T5z+9L0GsYLVRhOXB02ZZdqQ5CwmY7WeRSlN5yPkg6k=,tag:UBxMVWsfBwvY03lLUUz4yg==,type:str]
    version: 3.13.1
