apiVersion: v1
kind: Secret
metadata:
    name: lockbox-config
    namespace: lockbox-system
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:KQMNcaDcJe2eejjOqP69TtN7DD8xq2LQZDHT82L8SBZMSi9cQi+JWlfuhRDZN+ppNPAAgQ==,iv:qt+27UXsQFkJYeeIry7ow67tVN0M2Dg4n71WxAhHWls=,tag:8nFJbpVm8iU62mCjEKmZKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRDZ2dEF4OCt1STkvRTdH
            MkZjemF4ZXZ6QmZ3aWc0eUtDaWlaWGRYekNnCkZ1TDNrWUovQ3grcGkwNkdoTE1p
            aCt4SUh4SkdyYkpyUVNQaFdHWkF2N1kKLS0tIHpIZ2FzbWVKOCtpTGx2K3ZRYmVO
            ZEFUT3N0dndFWWNPcmswbXhGVkszN1kKwLPgFcv6z+ByOWp8rAAYyZbs819kugA5
            KNcB9bhjG0x1pzHaz8gvb9Gf917jcYZb0RHYQXatG/i+HgJlDEuKYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T11:50:00Z"
    mac: ENC[AES256_GCM,data:i49SR+ijv8LZLinB9zV+V75PVISTVMsm7GOUGwq8pkPAtrSdbgtNIbKEyU2RdCR4AdzuNPoPO2pePgfp2fZQ7BldoYd6nEWfRtfHoNpSHhANZhxhhDZFIhWFb3JIvI8NUGYU00Fm9aYL3ex8+X3z9+0P4tjpoMswQJXJ7pJvmuQ=,iv:ILra87dlTvUI25aujqlqZlVJlJvE7MKa43hHSLbWQ20=,tag:EDgeSq+DgiWrZyJMfWnZGA==,type:str]
    version: 3.13.1
