apiVersion: v1
kind: Secret
metadata:
    name: lockbox-auth
    namespace: lockbox-system
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:Sw2cqzY0DO9PZerrg/vyuFuhdrsylcaorYnwH9xzhKDSNITR7Xso26LzeQw=,iv:j7iV+eDxTsR13vc3QfsNlKCoTae112IR1Y4QOTxbrD8=,tag:9vr8TlmUQ3SQPOsVU82nhw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:GX0677RKo1F9AHL0yJJn5sRLUk5mFXX/Lkieppbqj/RECPtGu102Otm799A=,iv:TXJl6tGcclpyxYLjh828oyriSgAEbQluKktfcTuKm1I=,tag:9UFWeefAemnwWFUoCxLvEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNWFBNSt1ek4yOEthcmJy
            T3RMY29CUGFVSTlKcDhBVDFUZjdGZEJtU2dRClE3YlJQdDBwenk1T0xabFVrdGJU
            WDFMVHJ5Q2Z2NVBBR0RVOURTSTZxQmMKLS0tIFRjcS9ZeG5GRy9HOXA2NEFickgr
            cjRuSFBpQ2VXRk1jUXZtMTFnODNOUE0KTZofEjgHCnWYPzRO9CSMfR9n+qEOpcVK
            I5AhQAKL01XpkHCeE5ihU9EJS6sCSCIJoBuDog8fDMtGnlVH8k4sOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T11:33:22Z"
    mac: ENC[AES256_GCM,data:OSDJs4DFdkrJom9QvkEtxNpzMKWWEAI/n+8KFK/Cemyh2/3SXI0J8w38+nmTvsso14rPYAiuCufyO3yOQN0GydKzLU0QGsSOYEM748bqDvVgx+i1MJP6Xgnx2Q80Bzvy3/lOtDk+F/O+aa+wEDwsUgRRQ34C0VItoF/4kbSnjS0=,iv:5WIj6/xssAHWcPWC+qLAdm8bD4GgkFFEsm5ZIImxkV8=,tag:qh3u+PwJutE+0/CUwnwRHw==,type:str]
    version: 3.13.1
