apiVersion: v1
kind: Secret
metadata:
    name: lockbox-auth
    namespace: lockbox-system
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:y8PdBdC8mgBrNvoi7UHfCRAz9EtDOeS2jNM6yqEEAt7LX40j+igA4YXKfVA=,iv:utbqJfPCuOIT3l/HIkmNJ/v7wbPMuRVkxA8RPm/jvWY=,tag:kGzUWVQNSwb9GoOWQ3VYZw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:gg0ZWAHtFcN/f01qXcQAZHV8Pm/7JXmtCMFV1odIWQtqz1LgXG37Rxu+I6U=,iv:NAXLpcr6H0eo92I4TK1afUoydjApYbXteGNybU2Qz7w=,tag:F2fslZhhqhgdKnSvUNqS7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUDFlZkxGcE5zK05UeHNU
            d0dZU2NYaXRJOU9ab1doT2FzeDFXOWlZY0Y4ClJwRTdKV1k0VTAvTW5KM1hQdjFw
            SEp6OXFaVjZCL1RXMmdvdk1HbG9mQlUKLS0tIEJSeDVFVDBCQlBpa1JkZ3BBZU81
            OFRJVENMYTJndjhuQUFPbk83RnBjOTgKicyqDdBg1d+b1X/tkMB1o6v8N6B4wdRU
            Mo4THJ5YT9IAtX/fuO+V+crWB/jABJkNAp4RXXXJHsWmcaw7Ze6S5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T17:07:30Z"
    mac: ENC[AES256_GCM,data:Wbt24RMqDjnolkvWv4CgpDD+PC+uv/Ci25LzRiWmHySyXD0168vljBJ16UCp5JsQbKqSfzHj2DjTc2a4lOqE+rfMm0uvhQzofhBZ6KW76XZbYXTJX6UKBNidwMAtA3IJux1lGt+NuL7ultRHNvmZW8lV95KB49bx2zOo+Ip/CBg=,iv:C1d3KdbBW6NF0WN+Faes884cl1Im4s6xs3zjQMmYPgM=,tag:g7BJ24xqv9uI+cndCE1xSA==,type:str]
    version: 3.13.1
