apiVersion: v1
kind: Secret
metadata:
    name: lockbox-auth
    namespace: lockbox-system
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:OJK1UZY+ggT/g2IMcnXLq88uPg9vF0B04VerI6hJGyFw/WlEaQFB36Dynew=,iv:SGFLODGaY2k14A4lq5WrDaWvhvw9zJsmy7Ju12osj4I=,tag:ExFp7eGEL69uUBKnsVUa9A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:IOn32QjsSqThjfdtvQJzQ7YB5wh53BBZhrrJlL6xIcVKmLrakIvRHHDLteI=,iv:TTnqPs9TN0vVrRUCAFWfJUWyywUamnWGv49AFKqq9z0=,tag:99pEFFA9wQ0ziupAqitFiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZldNcFRNRDJkL2dNU0oy
            WFVLMlJrN0htcDRkOVMvRTRHWmd5cHhrcHgwCk5pcVNUL0dUSVRaUFFpZGhDZnE3
            U24rOEVVL0JUUWJYK0xLRFBvMGxVbmcKLS0tIGNONS9wSXh4WE9EWU9RMHN6TWtz
            aldPR0xJYm1KMFZUdjdnem90ZWZFbTgK6dGsQk+/4OIfUDqKQJe8cbfbl/xxSGbQ
            GIltdVy4M66j2r2esLvEVWhnTA2eYXmGtmsRvpXcJEJE16dE9i1/1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106pflxeud0c8qn0cxjvs9pknfnextllptzrdhtlxjvkn4l4qe92spm356r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:31:04Z"
    mac: ENC[AES256_GCM,data:U1O0Ak97R/bVeIWqLvYMixgUkyPwhSfQROybebHIrYyFARwEpvp3+JvvN1BOiyX+MqS7BVsbiCcQy7H/9Lrtvu85L8q3Q2oA7w3Gui+cBmrHRhdcTB4PUK7vSPuhXInATVpqglKBrEcid03LMBaXxqJSG3kTBav0FEKXywN0r0c=,iv:U5Nyjd4CmQ/+uMitn/VnIXD4W57h23u2p7ACAxzI9w4=,tag:FYvVzc0XcmTA67MsxKTBew==,type:str]
    version: 3.13.1
