apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  interval: 10m
  chart:
    spec:
      chart: headscale
      version: "1.0.17"
      sourceRef:
        kind: HelmRepository
        name: wrenix
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
      port:
        http: 8080
        metrics: 9090
      derp:
        type: LoadBalancer
        port: 3478
    persistence:
      enabled: true
      storageClass: fast
      size: 1Gi
    headscale:
      certmanager:
        enabled: false
      config:
        server_url: "https://headscale.cherkaoui.ch"
        tls_cert_path: ""
        tls_key_path: ""
        database:
          type: sqlite
          sqlite:
            path: /var/lib/headscale/db.sqlite
        prefixes:
          v4: 100.64.0.0/10
          v6: fd7a:115c:a1e0::/48
          allocation: sequential
        derp:
          server:
            enabled: true
            region_id: 999
            region_code: "headscale"
            region_name: "Headscale Embedded DERP"
          urls: []
          paths:
            - /var/lib/headscale/derp-map.json
          auto_update_enabled: false
        policy:
          mode: "database"
        dns:
          base_domain: tail.cherkaoui.ch
        oidc:
          issuer: "https://authentik.cherkaoui.ch/application/o/headscale/"
          scope:
            - openid
            - profile
            - email
          only_start_if_oidc_is_available: false
  valuesFrom:
    - kind: Secret
      name: headscale-oidc
      valuesKey: client_id
      targetPath: headscale.config.oidc.client_id
      optional: false
    - kind: Secret
      name: headscale-oidc
      valuesKey: client_secret
      targetPath: headscale.config.oidc.client_secret
      optional: false
