apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 10m
  chart:
    spec:
      chart: n8n
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: n8n-oci
        namespace: flux-system
  install:
    createNamespace: false
  values:
    main:
      config:
        WEBHOOK_URL: "https://n8n.cherkaoui.ch"
        N8N_PROTOCOL: "https"
      persistence:
        enabled: true
        type: existing
        existingClaim: n8n
