apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  interval: 10m
  chart:
    spec:
      chart: ntfy
      version: "13.5.0"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                NTFY_BASE_URL: "https://ntfy.cherkaoui.ch"
                NTFY_BEHIND_PROXY: true
                ENABLE_AUTH_FILE: true
                NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
    persistence:
      config:
        storageClass: fast
        enabled: true
        size: 1Gi
