apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-email
    namespace: matrix
type: Opaque
stringData:
    email.yaml: ENC[AES256_GCM,data:WasJCMJVa8CCJrLNP61TABXA2sa+2jF7Kqth9TLJlF14hsZeHiJz2ObgIaBRloXh5Ocilz50i/miXs4oMI4uxr3+I1pILedm8LwYQYkMHkyFod4wzZoVm4ovNisKO61tAQqDmTfTAN5xSJ+bnh+fGbvKkPnhHt2pPVC2F2WyzbC3P723A7D4X+rOmXpFrgztKuf8lBnKZIy8gSVttk2ibkWlAEd6qAb9l99Br6EAHCax9mBtXK/WYdjawfZyJhSQTa8rxY13+nICS6rcaQriEVS/lhITJBc1ZKTBK5RL10vdF8QmTHp5f2xXQ3YXMh/JSGZiA2pC5ai9hSVxN3fividvm2+bqgSiBoF5QXDhyOB+zkkfLUmLzSJ9j6YzNYnVmTlJYIbb4DLMZwzjfA3CSOZ4QjT9uC1w75+lNpKH9VP+0auT7XXc5sUMslH3h9FfDoEcQiRjAzhTVZrltVMhMYN1,iv:23eNHE37QFW06cAK45FWtNOv2/jN27s+bR5uMrw8ooo=,tag:unj/XRVzsGZAIemxNlHHLg==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmVTK2RoTWlVdVl2YlFM
            OXArYXorbUFBSGpqN21aWmdCMWtVZ0taZUhVCjc5UUw1OVp0VHFLcEVxT2g4SmtN
            UXZzanhnRkFNMTc5RjFCOVhpbHZEYk0KLS0tIEdNMSt3RnZLMHY0OE5mUkhPZDM3
            WExkUDNSQytlYmhKaWlURWpaNWt1cFkKF+0u+FWuU5aGt/4XMCJQ6yI29pynOoQA
            uWSjJdaPMcmz7CADxG9dxrNc5pIz8h/7OygETI9FlncDUmihm9RAEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T12:10:34Z"
    mac: ENC[AES256_GCM,data:LywRjpdNc8j61ULqOK04KlHF9ZVSSSW0jUIrKmBJ6dshLLGE4Kf8v9vNh4xe5bGT6isKT+sEzB208itsrZp4JdQ4QwS2mK5wO31E61Tr4M8Gkf7hDQRrYrFNT2vbpZIOSvtPN9qmcZTlvKMwyoJsYwhPLQj0mH77wwEYi/5krTU=,iv:NSUen90n9YIdEwBhOdjPSJ8LXbqqM4TxPmzWHVqkc5o=,tag:73lIyRpLQr3rJ9WAY4q0eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
