apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-email
    namespace: matrix
type: Opaque
stringData:
    email.yaml: ENC[AES256_GCM,data:DQi53a+TrvAHSgBUhbpx3iZKp5zwd7LtixEgaX5TowEfXr2kHRshX47VwjWxYQWwyU1gh8AB8fsWCFxMTNGUw9i2wTKunc2uJQM4dE/EWkTNehaV+y3OTvX16ZxyvxWjBGcjYXmObxRERnHGtQ6kKhDvHS1LQ/JDVVfyYRRbOrJZAdVr15LFl5P0ESHZY806jYjH9dvsyMqGzoS7NHa2fGEa1nMelwX1z0DTJ5sgWoGNMkSTkYHtqK82mtLOP/lOwyJ/850xu8ofBU1eVodTQC2Mo3ROzLP4mKKsual+a6ZwweIoTx9pAYS72ATsq4k3V27JdHpc666DCrjH3ZdlJ7sDcH1eTc2cxBF9/BliaHsbflxFzRPkaUKyxLY24MgScOUBaDXaae9UmrZY9/SjZPMJeD+COp1yroZt1DkjcXqX8kNSMaeypvZ/cNF2cQBtVe4lIDxmMKatdu+xrH4+lYK4,iv:ZEeUBtExMjF4zCcvbZMJmnZJNUyCF2ozuTAnZL80fwE=,tag:NG53ZLy5VpfzRLu4Ot52Uw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmVTK2RoTWlVdVl2YlFM
            OXArYXorbUFBSGpqN21aWmdCMWtVZ0taZUhVCjc5UUw1OVp0VHFLcEVxT2g4SmtN
            UXZzanhnRkFNMTc5RjFCOVhpbHZEYk0KLS0tIEdNMSt3RnZLMHY0OE5mUkhPZDM3
            WExkUDNSQytlYmhKaWlURWpaNWt1cFkKF+0u+FWuU5aGt/4XMCJQ6yI29pynOoQA
            uWSjJdaPMcmz7CADxG9dxrNc5pIz8h/7OygETI9FlncDUmihm9RAEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:23:00Z"
    mac: ENC[AES256_GCM,data:S0lQY+u58KW/KO/iomkxZ8hfLJHMjhvwoszPhQQNmSP+D5xILrnogey9NzObUlEh+ibMR7ZS9BhGSe3TLcI/X+I7fYks7GxnHm2HaF/7r1ZVJoFVv2Lu7LiTq+P1fLCg7URbiO3DwZUoZVB0c6rd56TSwe8NGdVoirzNPmmvGcs=,iv:+XVnCyGNA8pM+FIk5Q5+h+nq1iXxjJM9h4MRrLBvjK0=,tag:BHeE7d4TQ1nJMr7ca/2BGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
