apiVersion: v1
kind: Secret
metadata:
    name: matrix-smtp
    namespace: matrix
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sW1AUj3QwkKe0gX2Va5lzlw/A78=,iv:MBOWWj15DBWHW05eIRFK5PigAOfgM7BaxwMtDyFxIxk=,tag:7h/NuBjgUyHSmf0HMNvS0Q==,type:str]
    password: ENC[AES256_GCM,data:Bn2QZqyNQE+f7SBPXo8lRXf/7hyBDQ==,iv:5S35S+mbDChoHwEPJFj5Kt+62U0aPsB7jAS7dhLRR8Q=,tag:ES/9a30gTGqO9LhxApgoaA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QzZQNUk3dUdUWG8rNEVO
            VHgxbHErY3VRZ09hOWFNeXMzRXhqY0llMFFnCi9HWldVWVhYRzRac20rYzVaODh5
            OG5GTW5HNDU4Tlg4VXo0Q0tHWkdHam8KLS0tIGNWbFYwZXdsK2lXNzJ2cXdoaEM4
            ZCtEK0tRTXJIcmZhZ0NFZmtmNVZUdWsK+4qUtAJKqqqqpVnCM9MD8JqC1OEBweA7
            fb4WXiL/mkv+1cGSH+/ViR4a076PABtinNIQ/ltJFZ0wLd3TndlAXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T11:58:37Z"
    mac: ENC[AES256_GCM,data:9uSQraf5Ry/NPGVdpYXoy5lv72XGHpANDHlZkPss7uLteG0Ke0B09I4zj8pIMBtBR8BRS0dvoVjOoXDuxL6RiFRPWhprVkGR8j3U8plunME3dGTAy9u7X29Brt/dzo9LX9lh7CK9cBaAuZbFwaX3jo3yohustFzPoxjLFbJDRyo=,iv:9mOHHG5MGf6OO0QtosXDWK9HsdHMHQdDyCq7U+HyfUQ=,tag:kdJk83p3Z6N48uZev9yAwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
