apiVersion: v1
kind: Secret
metadata:
    name: matrix-synapse-email
    namespace: matrix
type: Opaque
stringData:
    email.yaml: ENC[AES256_GCM,data:DQdAyBHrkC1sNkQbV1J7FFXNhonv9akkvsOZJRV1IvB1aJJQfXc7+JZUoI+QETb7y7YjrzwXfyJTJOW/tqzFbbDigtQp4+3KF9kRcZgqYaf3kkPEsyMU1qaR+hvalEOplsvZsR7fzZMcpNE2x/bcSm0oPxFAPTZczrAiu5TDB7HhGNC4yD9JGX3NM8cy0CIoEeb8j5tDBemG1URHpZvK9DTXQZgbCGzSU9kLNiEGIHyc/aSP4DJQC5e3+zPvPJ6AAh7Ppk0UzTFYTVyLXbkwa+1DacR1FHx9QBX8PnxwL6aAFqfI/TUMOrwKFoGOPGq/aLQEDBUuj6LBu8KzPZZ4Vag6G++omAa3oL/XHHqblBkTq1PRzy3KxyXkaxT+HjwkvRhyyMoXoCPoGTHDvLzmAKR0//WrJJc=,iv:mluEwQ3RsHEH3e5c3DgNGMNIHYWwZbtPWil1MbrOg3I=,tag:BGl7M8ICS0Vcov7SLk2tHw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmVTK2RoTWlVdVl2YlFM
            OXArYXorbUFBSGpqN21aWmdCMWtVZ0taZUhVCjc5UUw1OVp0VHFLcEVxT2g4SmtN
            UXZzanhnRkFNMTc5RjFCOVhpbHZEYk0KLS0tIEdNMSt3RnZLMHY0OE5mUkhPZDM3
            WExkUDNSQytlYmhKaWlURWpaNWt1cFkKF+0u+FWuU5aGt/4XMCJQ6yI29pynOoQA
            uWSjJdaPMcmz7CADxG9dxrNc5pIz8h/7OygETI9FlncDUmihm9RAEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T17:19:25Z"
    mac: ENC[AES256_GCM,data:zJVViRn6eyqqsThWEKHCIPRpvgCxAj0tbTRl0tYjwJ2ovJnhDQZaTaAILIY0lwkqcgsJcAyjnzxS+CYBxHi+Ik/UepyA7s8AwPj/FizqLR1oMujrVZkVqbIOkgTWHHl0/tUhSoIRLK6oEhwL95gr4U2HAOu63peJIZvVpeqP6JM=,iv:oFlpslQnCTf/2RbmjSr7WRNNF+i+z1jstCsOEvLwKKQ=,tag:uxhPcyI7eYCCM/AhgZNFiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
