apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - pvc-data.yaml
  - pvc-media.yaml
  - pvc-consume.yaml
  - helmrelease-paperless.yaml
  - ingressroute-paperless.yaml
