apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: nextcloud
spec:
  interval: 5m
  releaseName: minio
  chart:
    spec:
      chart: minio
      version: "5.4.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  targetNamespace: nextcloud
  valuesFrom:
    - kind: Secret
      name: minio-credentials
  values:
    console:
      enabled: true
    persistence:
      storageClass: "local-path"
