apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  install:
    createNamespace: false
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
    redis:
      enabled: false
    postgresql:
      enabled: true
      primary:
        persistence:
          size: 10Gi
    nextcloud:
      host: nextcloud.cherkaoui.ch
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
      objectStore:
        s3:
          enabled: true
          host: "minio.nextcloud.svc.cluster.local"
          port: "9000"
          ssl: false
          bucket: "nextcloud"
          autoCreate: true
          existingSecret: minio
          secretKeys:
            accessKey: rootPassword
            secretKey: rootUser
