apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - helmrelease-rustfs.yaml
  - helmrelease-nextcloud.yaml
  - ingressroute-nextcloud.yaml
