apiVersion: v1
kind: Secret
metadata:
    name: anvil-oidc
    namespace: anvil
type: Opaque
stringData:
    ANVIL_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:kdg68Xe403QyI77+LYldat6r/SIHDDy+wagFRLeEbkcBaQlPm+DCv08eMNavehPncVG3QFo0Lp5SLLpPpjTFxC7iVRXKvm/oHbxScL4dOHVza7Gd189UdqmdvBA94A4mR2Qlo9euKfMR1zMFmtLMEUTK+CxCt19IBReJOq6v1+A=,iv:r6hGSEfWSeMCv3DqjJARnfbNxxmTBukIE2ds3KSe7F8=,tag:EaLUMxIAwjs+y+avOeXmcg==,type:str]
    ANVIL_SESSION_KEY: ENC[AES256_GCM,data:KmN2VgSG8asyfvC4AhlrknRpMKSIZL93Uiz2D1p1iGo+b/zwczh7ADHzhKE=,iv:JvelOljAlWYjS+LAc42nc8AIxFgs8jkKrL9a0FCvQ24=,tag:sykKQYOf63ZYLBngfT84Mg==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWCtLSlRzemNvUjJRWklz
            bVdENHUrNm1JMzNTSlo0ZVNlT0xtQVFVbGhRCllkT3ZtYWtvUjVyc0ZlR002bHg0
            c1d3SnM2aktvTlZnM2VxUm1iSlVPc0kKLS0tIHlkSzI1Z3EyZmp6QzNMaFkrbDgv
            NWFrYjU4akpad01uZjBXWFNFNVdRZzgKXTJu/1eUN3xTvqxlugb/04wiyHJrIU0p
            UykPZ/ntQgrQnShE+9mumDOJK+b5YqYO+xfNULYmDHxlhhF6FPkycA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T20:39:22Z"
    mac: ENC[AES256_GCM,data:rSsJRrxsgmFyJqw+syrjuF1UP0xAej17jMpYDMvDphOe8fkQue0i3tB+CNShxv6P8HGK6BmDGffYBUzAbwB29rRogxLJIooBDTxI+/px8FajJCPBWNYAtacuVI54TZAKUxokDF0EhgteOLf12HfsN5zOFFSEckR4/WjO4lixhnQ=,iv:qctVtkqr4anDe//DRue+P+C7E5W0ATl9burgNaWfvm8=,tag:9yrHUwaNaMKjyt+6aqYtcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
