apiVersion: v1
kind: Secret
metadata:
    name: anvil-cf
    namespace: anvil
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:g0A9fuJ0MvkttoBQEpgLpKbNKZ8ySA28kTgbzyml8nNlaOMg5Z4HTm9VO6uf2iv7R+cKZY1uhW8LqKqd,iv:tzDSwoCpcJ46Bvu07mPSJX8ugexN3H6Il5mczL4h1WI=,tag:JK+2p2W4OBwB1plSzKUVbA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZWZYbjc4THEvT21EbmdT
            Mjg5WDRzcTkya1JQeHQ4bmd5VGdFYnhTVXhBCm9IQVRHaytLa3RBbkhUdzFGd2dS
            NitybTRMRFlKMU1hdDlYUlpoeDc5SFkKLS0tIFo5Z1FMcFNsUXZDSlRYc29Ha0F5
            alo4QyttQTl5aFVHRVFOL3gxSnBsQVkKY6NII42KgrDPLpgXclkiQDBHMavNvH9v
            e9iyVvFwg2P5qPrryChEPktmtuxDr3f0h0cDSlqbqYUnPEzrQTcUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T20:32:50Z"
    mac: ENC[AES256_GCM,data:1/1Nb4+rZwqQLYM5bFofQ0xwTW04v0hNq7Fc+J5kumLTG1TkhPnOySiuj991jICPfHaswHGibiNeGLy5RjzMUp56fi632mQ3eTi1vCJka3F8XzvuTWTntEF65p4ED0MnrBxVwH40KN1y6XK/wlTm8ullOactfz25Zm4NhpoWk9A=,iv:I9djNMXW9iuDl1imbZ2vk/4c7x+nvzD7fwsQn+q514k=,tag:7qR3y7bsVI2ZVXH7hTj8GA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
