apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: mc
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:jLvo5MN5F7Ltv83sEHWDMWyyI/9x6aus5WOimOWkapCCMfOazgYzZzcwaDZWOfJHLVf1Ras6kG6TUmu7,iv:1lVx158eT7a+tk7my+DSh/zvUXh3t0UeDbZSkoqbQCQ=,tag:gVE4zIS0dtY1/BPu5iXjIA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTkZPQWJycGdrL3RsRlkr
            MW1pQS9VZDRXVG10RkNZN0pSbEV2TkF1QTFvCktnM045a2NyeWxIcGdjRUs3cXpV
            V011UVVGQWJZTUF3NVNKR2IzQ3dxdGcKLS0tIG1rL2ZKRGtxWVZLTThLenNRdUdu
            N3V5K0x3OWd4OEEwQUlkRkx4SDVmQnMKLHRm/HVWR2Z/DIKf/8F7vJkQnZWAllB6
            3IaUOjo4S3rJCKBuZrZuAGoVqYB0asCmZsLiYD4jsSmiviQSqDZnkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T20:19:42Z"
    mac: ENC[AES256_GCM,data:QkSXeo2vZyZ17MD+kJHxcdAx/F9oBRAPUSApbefYHgPBGK1eVC9Jzk38bSYuQ26yymzFnxy6wkMSRNcYGrY7BuY6tb6EMfnyV0GvfyRYHotHmJSEmTrqM8JsOsoujDzQ8silMhZhyEIX27tUeLQbQcClJqvrXb91QGD3Iz25BCc=,iv:cKalk8sK08mMIn6fFCnnDT1T0vxhyQMIjDUDAeDIRAo=,tag:iw8q4GJwLNlHGAymhyYz0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
