apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - cidr: 172.26.20.10/28
    - cidr: 172.26.20.32/27
    - cidr: 172.26.20.64/26
    - cidr: 172.26.20.128/25
