# CiliumLoadBalancerIPPool (from modules/cilium-l2/main.tofu)
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks: ["172.26.20.10/28","172.26.20.32/27","172.26.20.64/26","172.26.20.128/25"]
