apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  install:
    createNamespace: false
  values:
    server:
      ingress:
        main:
          enabled: false
    immich:
      persistence:
        library:
          existingClaim: immich-library
    env:
      DB_HOSTNAME: immich-postgres-rw
      DB_PORT: "5432"
      DB_DATABASE_NAME: app
      DB_VECTOR_EXTENSION: pgvecto.rs
    controllers:
      main:
        containers:
          main:
            env:
              - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: username
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres-app
                    key: password
