apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  install:
    createNamespace: false
  values:
    server:
      ingress:
        main:
          enabled: false
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
    env:
      - name: DB_HOSTNAME
        value: immich-database-rw
      - name: DB_PORT
        value: "5432"
      - name: DB_DATABASE_NAME
        value: app
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: immich-database-app
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: immich-database-app
            key: password
