apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: immich
spec:
  interval: 5m
  releaseName: immich-redis
  chart:
    spec:
      chart: redis
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: flux-system
  targetNamespace: immich
