apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  install:
    createNamespace: false
  values:
    common:
      config:
        vectorExtension: pgvector
      postgres:
        host: immich-database-rw
        existingSecret:
          enabled: true
          secretName: immich-database-app
          usernameKey: username
          passwordKey: password
      redis:
        host: immich-redis
    server:
      volumeMounts:
        - mountPath: /usr/src/app/upload
          name: uploads
      volumes:
        - name: uploads
          hostPath:
            path: /data/media/immich
            type: Directory
    machineLearning:
      enabled: true