# Kustomization for Traefik ingress controller (from modules/traefik)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - middleware-security-headers.yaml
  - servicemonitor.yaml
