apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "no-referrer-when-downgrade"
    contentSecurityPolicy: "default-src *; script-src *; style-src *; img-src *; font-src *; connect-src *; object-src *; base-uri *; frame-ancestors *;"
    permissionsPolicy: "geolocation=(), microphone=(), camera=(), fullscreen=()"
