# Traefik Middleware: security headers (from modules/traefik/main.tofu)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "no-referrer-when-downgrade"
    contentSecurityPolicy: "default-src 'self' https:; script-src 'self' https: 'unsafe-inline' 'unsafe-eval'; style-src 'self' https: 'unsafe-inline'; img-src 'self' data:; font-src 'self' data: https://cdnjs.cloudflare.com; connect-src 'self' https:; object-src 'none'; base-uri 'self'; frame-ancestors 'self';"
    permissionsPolicy: "geolocation=(), microphone=(), camera=(), fullscreen=()"
