apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: 10.0.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  install:
    createNamespace: false
    disableWaitForJobs: true
  upgrade:
    disableWaitForJobs: true
  timeout: 20m
  values:
    global:
      kas:
        enabled: false
      minio:
        enabled: false
      gitaly:
        enabled: true
      appConfig:
        omniauth:
          enabled: true
          allowSingleSignOn:
            - openid_connect
          blockAutoCreatedUsers: false
          autoLinkUser:
            - openid_connect
          providers:
            - secret: gitlab-authentik
              key: provider
        usagePing:
          enabled: false
        object_store:
          enabled: true
          proxy_download: true
          connection:
            secret: gitlab-rails-storage
            key: connection
        artifacts:
          bucket: gitlab-artifacts
        lfs:
          bucket: git-lfs
        uploads:
          bucket: gitlab-uploads
        packages:
          bucket: gitlab-packages
        externalDiffs:
          bucket: gitlab-mr-diffs
        terraformState:
          bucket: gitlab-terraform-state
        ciSecureFiles:
          bucket: gitlab-ci-secure-files
        dependencyProxy:
          bucket: gitlab-dependency-proxy
        backups:
          bucket: gitlab-backups
          tmpBucket: tmp
      registry:
        bucket: registry
      edition: ee
      hosts:
        domain: cherkaoui.ch
        https: true
        gitlab:
          name: gitlab.cherkaoui.ch
          https: true
        registry:
          name: registry.cherkaoui.ch
          https: true
        minio:
          name: minio.cherkaoui.ch
          https: true
        ssh: "gitlab.cherkaoui.ch"
      ingress:
        enabled: false
        configureCertmanager: false
        tls:
          enabled: false
      smtp:
        enabled: true
        address: smtp.protonmail.ch
        port: 587
        password:
          secret: gitlab-smtp
          key: password
        domain: smtp.protonmail.ch
        authentication: plain
        starttls_auto: true
        openssl_verify_mode: none
      email:
        display_name: Cherkaoui Gitlab
        subject_suffix: ""
      monitoring:
        enabled: true
      psql:
        host: gitlab-postgres-rw.gitlab.svc
        port: 5432
        database: gitlabhq_production
        username: gitlab
        password:
          secret: gitlab-postgres-app
          key: password
      redis:
        host: gitlab-valkey.gitlab.svc
        port: 6379
        auth:
          enabled: true
          secret: gitlab-valkey-secret
          key: password
    gitlab:
      toolbox:
        backups:
          objectStorage:
            backend: s3
            config:
              secret: gitlab-s3cfg
              key: config
        extraVolumes: |
          - name: custom-license-key
            secret:
              secretName: gitlab-license-key
        extraVolumeMounts: |
          - name: custom-license-key
            mountPath: /srv/gitlab/.license_encryption_key.pub
            subPath: .license_encryption_key.pub
            readOnly: true
      migrations:
        resources:
          requests: {}
      webservice:
        minReplicas: 1
        maxReplicas: 1
        autoscaling:
          enabled: true
        extraVolumes: |
          - name: custom-license-key
            secret:
              secretName: gitlab-license-key
        extraVolumeMounts: |
          - name: custom-license-key
            mountPath: /srv/gitlab/.license_encryption_key.pub
            subPath: .license_encryption_key.pub
            readOnly: true
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
        autoscaling:
          enabled: true
        extraVolumes: |
          - name: custom-license-key
            secret:
              secretName: gitlab-license-key
        extraVolumeMounts: |
          - name: custom-license-key
            mountPath: /srv/gitlab/.license_encryption_key.pub
            subPath: .license_encryption_key.pub
            readOnly: true
      gitlab-shell:
        minReplicas: 1
      registry:
        minReplicas: 1
      # Gitaly - fast storage for Git repositories
      gitaly:
        persistence:
          storageClass: fast
          size: 50Gi
    registry:
      storage:
        secret: registry-storage
        key: config
    gitlab-runner:
      concurrent: 5
      runners:
        config: |
          [[runners]]
            [runners.kubernetes]
              image = "ubuntu:24.04"
              privileged = true
            [runners.cache]
              Type = "s3"
              Shared = true
              [runners.cache.s3]
                ServerAddress = "rustfs.gitlab.svc.cluster.local:9000"
                BucketName = "runner-cache"
                BucketLocation = "us-east-1"
                Insecure = true
        cache:
          secretName: rustfs-cache-credentials
    installCertmanager: false
    certmanager-issuer:
      email: admin@cherkaoui.ch
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
  valuesFrom:
    - kind: Secret
      name: gitlab-smtp
      valuesKey: username
      targetPath: global.smtp.user_name
      optional: true
    - kind: Secret
      name: gitlab-smtp
      valuesKey: username
      targetPath: global.email.from
      optional: true
    - kind: Secret
      name: gitlab-smtp
      valuesKey: username
      targetPath: global.email.reply_to
      optional: true
