apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
resources:
  - namespace.yaml
  - pvc-rustfs.yaml
  - deploy-rustfs.yaml
  - svc-rustfs.yaml
  - gitlab-public-key.config.yaml
  - helmrelease.yaml
  - ingressroute-gitlab.yaml
  - ingressroute-registry.yaml
  - ingressroute-minio.yaml
  - ingressroutetcp-ssh.yaml
