apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    KIMI_API_KEY: ENC[AES256_GCM,data:cqBy92VWU0XQSoS9gFDalW7lmZ2lgAHxL02cFIk7ebMWpUiwQ2RODPapvwoxx35C3OkM5pJTkzzi8ZE787XsHSFkJgLTAe9F,iv:UfOHVHeDwyMxFRVYBIP6wyMoahdSdAEvzOASs4xY3DA=,tag:nMPNHFO3Kbc/8F7Qu0rsyg==,type:str]
    KIMI_CLAW_TOKEN: ENC[AES256_GCM,data:XzCHWKR5jp6d8HXnzmFSPtm/D3JbSjs4/sRwVTQ=,iv:xWWmEjLlpUyMVWj3s/G7krEO4hSxFPsv+grWbvojjQg=,tag:K+oIjFb9K0OPLQnJx+IfXQ==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZDZkZC9hZmtCWERQSHlj
            bkZKSXFtZlhxUVNwNFRIdWdzMlREK2QyVVN3CnBlZUtkcVZHQ0g3dFpoK0UzNUJy
            dUV0RlJYNFBkWXFCWDFmcVp4N3YrUk0KLS0tIEl0YjVYTno4OWZwUjFKcnJZWlRp
            WVNCN2JJdGl4TUQrWDZpY2hua2lzYXMKlXP7eRr58hIbIfRAvrv92kHxsQTZWNXP
            5bCZYt3yx4pSYL1CAtB6j9pjz0J+p+L16EBiCCv1fB3iPI8leWveew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T11:17:52Z"
    mac: ENC[AES256_GCM,data:P8mbSwthhFjz7iGwoRcN6cwWoRHlnuMhnDrKaBZ/iIlwOfKOuHCi3LvsuqP2PIkjN484myVzHe4zEDNfXJVOa83um5s47nYMyZczHtvt3WK1OkYjuUIfWnRdge/+ZaIQNoMj/oHFtGGMtBQ3+TVyuPRJ0CNjDD7FiFcBxAY1cCk=,iv:FGPMN3p92WPB+9tOZbiZm8uoLDehBXhR+tIjDkDK314=,tag:JoyGx3WojWDjDkUkCE/ONA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
