apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - ingressroute-core-web.yaml
  - ingressroute-core-grpc.yaml
  - ingressroute-proxy-web.yaml
  - ingressroute-proxy-grpc.yaml
