apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 10m
  chart:
    spec:
      chart: sonarqube
      version: 2026.1.0
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  install:
    createNamespace: false
  valuesFrom:
    - kind: Secret
      name: sonarqube-postgres-cluster-app
      valuesKey: jdbc-uri
      targetPath: jdbcOverwrite.jdbcUrl
      optional: false
    - kind: Secret
      name: sonarqube-postgres-cluster-app
      valuesKey: username
      targetPath: jdbcOverwrite.jdbcUsername
      optional: false
  values:
    community:
      enabled: true
    ingress:
      enabled: false
    monitoringPasscode: "SonarQubeMonitoringPass123"
    sonarProperties:
      sonar.core.serverBaseURL: "https://sonarqube.cherkaoui.ch"
    postgresql:
      enabled: false
    jdbcOverwrite:
      enabled: true
