apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 10m
  chart:
    spec:
      chart: sonarqube
      version: 2025.6.1
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  install:
    createNamespace: false
  values:
    community:
      enabled: true
    ingress:
      enabled: false
    monitoringPasscode: "SonarQubeMonitoringPass123"
    sonarProperties:
      sonar.core.serverBaseURL: "https://sonarqube.cherkaoui.ch"
    postgresql:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
