apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-oidc
    namespace: filebrowser
type: Opaque
stringData:
    FILEBROWSER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:R/4wMxgpVfz74Z4Z2YaCCjENVvptOuIRxNjC9v5SIQPIDqtgRCZIOA==,iv:a8cRNauEyeVzhoDs1dZ1G8egpen10vJeH/58gLWZMiA=,tag:ujo1UD4/5RnhUTR66xd3lw==,type:str]
    FILEBROWSER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:bKB4oMPiMbe0GqrTP+OlT25SvhKKU4aTKTpoNhmdh39PAYVqQobdrFhQensDkP8o9E7DnLrMqXFvnS+RIM26B/XSptmpbYDiqc3fPB0qOaA54w3siipmRB53wcMmpem0P7MBvRXKqsVhYZ2/os86skWkjvtZ/Ho20IfgZY6ojQs=,iv:6VjKhKDYkSW5+c2Jdbl/MlQH+rXW6ppFgrZ1SC28O28=,tag:KQ74PwQS4j+9ztlZNK7yzw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0akNVcVluRU1MdGd0L09M
            SGd3YXY3N0dHb252ZnQ1Ry90S21Gc3pQWVJjCkZ4ZUF0TU9GeVhqMHRwak9SQ2JQ
            bDhwRmRaZ05JWjJoaGdTajNmbGJLR2cKLS0tIGJPZExVM1Z0czl3ZHo1Zm8xbVhv
            QUI3TXVYUjlmYWJoZlQzK2MwSHJkMDQKPZrmizH+2fdpkHx7OkmEulnEbat4ASKt
            iFzAD1QbGAZiIZy16TnH1oKpYX/AeavQ/vJG0dDJ1X7QefglYLjdvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:8ICe21wCxi3MSDbBPN55fQ2oz+PK1uNRm++YWw1Tf/Y8cYKGOFFsFZod6ARMQfGMC/4t8WtgW0AELAPF/dp/Zu2Z0Q3nwhW4L/MIzajtf6ts7wdDWbRoTm90f1CyWhrJ9J2xg/d38LIVKNdoI/g2/B0K3io6v8aGbxe147I0iT4=,iv:rva5nf45Rheu0XSMbZdUL7jO5/dtbl8+jy2AxghPk68=,tag:wZg8Khi0V39xeunZ8fFRBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
