# HelmRelease for kube-prometheus-stack (from modules/monitoring/main.tofu)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: false
  values:
    prometheus:
      prometheusSpec:
        retention: "10d"
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: "10Gi"
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: "2Gi"
    grafana:
      enabled: true
      # adminPassword intentionally not set here to avoid storing secrets in Git.
      # Options:
      #  - Provide a SOPS-encrypted Secret and configure grafana.admin.existingSecret
      #  - Or set via environment at deploy time
      persistence:
        enabled: true
        size: "5Gi"
      ingress:
        enabled: false
      dashboards:
        default:
          kubernetes-cluster:
            gnetId: 7249
            revision: 1
            datasource: Prometheus
          node-exporter:
            gnetId: 1860
            revision: 21
            datasource: Prometheus
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
