apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: alloy
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    controller:
      type: daemonset
    config:
      content: |
        loki.write "default" {
          endpoint {
            url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
          }
        }

        loki.source.kubernetes "pods" {
          # This is a simplified example; you may need to adjust selectors/paths.
        }

        loki.relabel "default" {
          forward_to = [loki.write.default.receiver]
        }
