apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: 6.53.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        path_prefix: /var/loki
        replication_factor: 1
      storage:
        type: s3
        bucketNames:
          chunks: chunks
          ruler: ruler
          admin: admin
        s3:
          endpoint: http://loki-minio.monitoring.svc:9000
          insecure: true
          s3ForcePathStyle: true
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
    minio:
      enabled: true
    # Explicitly disable simple scalable components for SingleBinary mode
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
    singleBinary:
      replicas: 1
    persistence:
      enabled: true
      size: 50Gi
