# Kustomization for monitoring stack (from modules/monitoring)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - grafana-ingressroute.yaml
