apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        size: 50Gi
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 720h
    promtail:
      enabled: true
