apiVersion: v1
kind: Secret
metadata:
    name: headscale-oidc
    namespace: headscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:CWR+uAldUQB9F7oOZqIgZND5tyZN6afsxpK6A1C/MJGGUfUcby4c4A==,iv:fHJk8t6dVDX36K7LHpCuF1RebUyJaBue20zjbp9h5+g=,tag:gBzH0xHSrDDfsj0B1CHk5Q==,type:str]
    client_secret: ENC[AES256_GCM,data:ymTC9LxHSyin8RFD4AvQEeBdLXCgAJR99vym+UkkJGsGps3IEcCyXXkX9mrai/dZu7HqDKSBRs2CUR4uXLECe1Gp1r/HZ4jdUnxQIqJEw9a61tGQ/B/VOF1yFdevAb3hI8UK7ktPUsHeHoT9+L3Ow3RRKBB+WowDcZ8tNC3RPYM=,iv:VaAEvsoDsAvdCx2vnlhtWyrxxl+tBLp8gRqicUS0BAk=,tag:qTqiSUjZZ2H31vx2xIYVQA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUUk0K2RZblBJZjFVMUg2
            dzA4Y3REOUMyb2R5R3RkTHZlWnpqVE40a1RJCmsyTWdMRUR3SVE4ZlhKUmtVVXhj
            T2NNWEk4RC9IMldmZVlXNjhDcFRYd3cKLS0tIEkzNUlNRURmZkE0eDl2SVdUUVI4
            eklJSTNsUDA5MjREMUMzRUVBMlAvOUEKsJDxfw2mBMvNN+u9UBc3TMzJcuQxn4GX
            lDcvl3OamtUk7hSwqu6k3DVnQd12mNlGoYqaaJsyYoViI2RNZierTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T13:40:08Z"
    mac: ENC[AES256_GCM,data:DdLGDXBnCzXqXgtQn5e6deUDIo/PavsbewBww0gsWG6WsrnfptaQ2ifYC3LIkJSodLVWPRCpS3djm1mElF5PfFtYHA7mQ52yN87NuOzv8ELpe5FJjXzTKlDlNcZkjRgYdZ5MUbev6mkszxctza0ZanWKsHPUuQHlLKCNcXxke/8=,iv:FvfKoGhdjBARz3lrdaCsVMPVlHB0D5VvQq1DZ0phVLE=,tag:8ypJceIbGbQy8ZCFBphAzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
