apiVersion: v1
kind: Secret
metadata:
    name: authentik-smtp
    namespace: authentik
type: Opaque
stringData:
    email_username: ENC[AES256_GCM,data:qmfsmoySfN2bP1yo82MTqtrkOK0=,iv:Rm06hiR3Tbi8uZPt/SUytlqovZJBqJGTaNjlFlJp+lw=,tag:uToY1UtUlMnGlat1Wmt+eQ==,type:str]
    email_password: ENC[AES256_GCM,data:IkOVWc/HCc5t0iilu2C2ug==,iv:SNJwLQBGUPhdiCNbSxKabO/zQjU3RmqDUVYHPeGH3KY=,tag:1iZb5j4QbLkBXayOFn3uBA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFdvMDJVZEYzcVk5NVJK
            VTZqNHpOckhvK1lLYi82cm13YjQ2WDd2aWlBCnE1ZFM4bEJyZHRtdkNQVi81Sk5x
            SVh3OGN4SlpiRTBKRWFIZDZxM1pybTQKLS0tIFZreGxPbEZPYXNsNjFNSGwyN1Rk
            TXFnSTFGWFcvQlRIVm44U21ZNk90blUKS49Ps1CLf8S5Cn0bE7sE/09GwYpRlbwL
            HfCytXv965lz0GrwhFdpN4nLn9ccpXI2Y607Bas6IxEMT2qFdDFGuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T17:19:36Z"
    mac: ENC[AES256_GCM,data:XlQxqkOER/kAnKdh27qwC0YP0j+3Z6RUFq1vcCR7E/1IV4HNmNwmwvghTLns4Sdt92+u0m2kEsYiE5bfeRf/Xeu5LymZ83k8JpiSkPVdXx7KlDIEVQdatxics+HKC+eKswswapTeTtp9v7D9LZchM6qFcz/0seagUt3qarxec3M=,iv:JV3nACJc0IP1hCpGpy2WCET9DiZLd7MXEw6ozCaslAs=,tag:w2gQDNemlTuTuAkaxhCA1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
