apiVersion: v1
kind: Secret
metadata:
    name: authentik-smtp
    namespace: authentik
type: Opaque
stringData:
    email_username: ENC[AES256_GCM,data:qmfsmoySfN2bP1yo82MTqtrkOK0=,iv:Rm06hiR3Tbi8uZPt/SUytlqovZJBqJGTaNjlFlJp+lw=,tag:uToY1UtUlMnGlat1Wmt+eQ==,type:str]
    email_password: ENC[AES256_GCM,data:TgOlpNRjd8T1RxiW74Z0eKvjGRZFLQ==,iv:7QUporee+X4YwJvxOYNjETEGpS+H6fsUupeTPnYheww=,tag:n1qHnJZaS3pC7+sX/I9yeQ==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFdvMDJVZEYzcVk5NVJK
            VTZqNHpOckhvK1lLYi82cm13YjQ2WDd2aWlBCnE1ZFM4bEJyZHRtdkNQVi81Sk5x
            SVh3OGN4SlpiRTBKRWFIZDZxM1pybTQKLS0tIFZreGxPbEZPYXNsNjFNSGwyN1Rk
            TXFnSTFGWFcvQlRIVm44U21ZNk90blUKS49Ps1CLf8S5Cn0bE7sE/09GwYpRlbwL
            HfCytXv965lz0GrwhFdpN4nLn9ccpXI2Y607Bas6IxEMT2qFdDFGuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:23:26Z"
    mac: ENC[AES256_GCM,data:yh7eDy6aYKYM3QFoj+/W/+TINL84lBoAAG81Nto/REpVh0G8AfwsfH32UhWCTqPqjwQ++wVVSq2/8CI+RTvDINC/9dj2Sc8MBQdGJGzWmieN+WR8iw6EgGPOmmSIJWX7ELlTsqH9779qdxhw772aQ+zDvBGlm7EzrMSKdHq7HUI=,iv:SD3eyB6Fr8BxGzog8XgZqU4CPD3W/oFZC9jN0/67aZQ=,tag:l8qzHiVV+lMRxSeYzO4zig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
