apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: minio-operator
      version: 4.3.7
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  install:
    createNamespace: false
  values: {}
