apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:NXdfzqLayOE+ZzUE7dqLA7pDp3jUXgLUqr26pKIVjAy+cg32djaw8fzJ63+eMpPFm8AQ0fy5yeP5LgSYreG6wQgXYU/z58amUmUYGmvvZyoLH7+Kc/abrnzBlN0IxuSQHAzRTSW4RwvKjGkboUgcaccHs/SdJqNRVD5bS3/nj8olpS0H8UeB0OOciKC7nuyaQS/CocjQEshQJK3QDfemUipif1/s9qaKIq3MnuzeFuFiXSFf9dLp3/bLUOJa4C7B3Vh9WhUEIxc=,iv:DzgGirgekIqfy5PCHqvDtsx9OsxaTFskbAPGPfEfFxc=,tag:1ef4EqoN/KwrRn2oP+/LZg==,type:str]
kind: Secret
metadata:
    name: scolx-registry
    namespace: scolx-demo
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT0dZd0ZPMEhyMENjdFRm
            WDhmbi90YkR0QUFDbHlJbm5YYVJPNXNJYUYwCk9TVnZnSkxEeXVPN2pZVXVkQitP
            SzZDZFdaMlpYeU54VVB2YnhPOHZVK2sKLS0tIFFDbjJBUTM3OEQvK1NlUzRSQnFH
            WkFGL2V5d1p6bVlQTmZidE11VURMdlEK8B/52ZG++uFqibUVUXb5uVO8E3XtfQIR
            VEeicOOf4I8W8ZlbIh1SxHPw0F4lerE3l0jv/1gMyP6Bji2PgBgdlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T17:59:40Z"
    mac: ENC[AES256_GCM,data:a7/pKWPZztQCGQBlkKjf9aZ2teRVpBqHXeINq2OJ8SbDgWq4vBgGpE+Atw1O/wRlenHZKcIqv8I/cqD0c/Yqr6s8CTaXwiy/dQkpZz/Bq6wjBCMDeVdqQluQg7a4DiiypYiMFnG7No1s206oWR5Q8X2SHnBZ3roGUBOiOC19a74=,iv:luaSdr/JttGB1xQMSlAAm+co+TZxF0dlnvO5GxcEjtE=,tag:AzF6uMOZNA4VCY3a+Qj2EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
