apiVersion: v1
kind: Secret
metadata:
    name: gitlab-authentik
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:i0aFr+l9TFrwFNu87eyC+8Vg5sEAVfk6Z+s3CIg8gReh/7rzZQHz8HTdAKHCSBmtAtdDvxA0nUYKWHlB4l+AeA8gHrNgO3glcjUxAIPERxkMSpQ7CPwec9eEahgKzbU34BvK+4yVhDyFuD3SVD7Zj3V/jBhDIs8sKs8FDLFSaJ5wE47TlWADsZjRsj/sHUSSNvvSxWqeFrF8uk0ZfA37bL39xrfR+GWOkyUMZPSlw8LDhutFcP1c/uztMr5LlOIQGmvASWEpC95JR6aG7momhHSUiIql3/nCk96ivYcqne971w9HOKyUQLJ0Ye2Vq3tnhdHnGqIshB26ElaHigJ2BGPZqSvqotNzADIXXkzomy1tcAWyg3NeOWvyBDAR8ao5WgCzAQEParvZ5ikD8jROAaqvvG3eTz5d3G+dHXIAy3ngX7vcMFskv+12UcP/vWtVhlEvoJlkUVeQCmbD6MJwmOucPPW1dEEXWd0Ue/V1UFuUfTmpK5Me74PTAMImlNRIOieO0FEQQ+WusAPnHZ5+ckBN/W2F7yYHuZO3V2tou3fvXkM2SWAIKf8irHaT0tAeBzEax67gBCPBxmRHd+Lp1PsrjJrOhPQrtkpHo494ZyvesO0sDAerv606WdRRw7a5/LqsNBSWeuHeBDL9J3eQgYyTuzed2YfNNgdZvFaMLJWY8AEYy/YzADvkNspZmvE4lV8dqJXjV9InBKwBnK1RPyQMC2YxSODXa48s6PJWXuJq8Zk723n6andvyyGCIKVxSAU9oNkdeUDmztiQyEo2DUG3wM1vm9zZeto4ANvbbBZIWxDOfThH6vnud/mSW1lIvnxIUGbi,iv:zOyK4T/ZRb38nVn+wwj0LNPOxfv/igzXOXdm8UViuCQ=,tag:M3m6VBmpAewxBsbuY/7Eog==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1anZnT1d6Q1NVMUVJV3hv
            ay8wM3R4aTJFOXNGWE1lSEo5VkhDTzRjUkR3CmxFU3ArNVJ4dERKMjZEd0hSYzNK
            d2YzM0lHVGF3M2h0cWlWdUkyVEtoSDQKLS0tIExnbGN0Z29QckprTEIweHB5NVY2
            cS8xMUdtbytwVUpjOUR1aXprRWR2SzAKpnTAr7CFvbvvrwxqWzSDAPFa40wcgQPL
            FVlrucskr8aSdsxONzTe/gT/zzucqPcsE0rYMXEopzJmdbAzaHCotA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T12:58:26Z"
    mac: ENC[AES256_GCM,data:fwLGWVaLGaFfbgCQ+VGleOyCQJFAbtHawIUmYHLZwBW5zYcrMHjsM7P2dkPqXOlMtqA05FhkTiZSOhdUM7lhy6Fx39wJr/w/Bsp9c3X5VrYuRCxeMQD5sCt4Qab3/0rPp5rGVWUuc16OZDXDBmcZeubIK1BXdX6pEkV2y5MkuXo=,iv:p74ek8AiY1kMGXXikYO8TLDJxUJIboNMdPcbx0i/i7o=,tag:PgtVMwZhkhqx4x17TeyJyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
