apiVersion: v1
kind: Secret
metadata:
    name: gitlab-authentik
    namespace: gitlab
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:YnT7MR5Xrmm3NhMNiZ7GO4IlSqwAgkv1gOJwqRLuehwzeBlcMOF8vg==,iv:34wdu5N4QzQQh+r802M3LjOyqGMK1nBh+H5fSJd87K8=,tag:XMbEQuQQ8CVYoKEpLwNG5g==,type:str]
    client_secret: ENC[AES256_GCM,data:ICyZZKm/ZOLwz0SyFd8lsYkjwjNGQxIYEdhhufbnkHLvku38yLWbYC3Kan9x/8XtaUXF2FRaO5KUR8BROaiHqqW/cIH5keGrauOLv0kM3cKJWC5rWGSTD4qWkKGnNJAQbTFusgps8aU83oZiUhvys28I3Ndd4LYV9fCsD56r4BY=,iv:yV0JEiC0RY2iJrLFp8tzFpuAXx2pqla2OLqzOyP1ObY=,tag:FnIX77YyYvfw1tnG/39iqA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTzdsbWRQNllZM2poU211
            cXAraDROQkgxdXQ2SUt6UUZhSnpSbW1yZTNjClNBcjVpYnJuaElmK2xIZGppUnNy
            eEtNUXk4TXByelljNVNzQ3MySXVQUVkKLS0tIEtVcTJHc0RpWGRVWTE4enB2eW5H
            NTE0S1FkbFJYSGJEQi9CeTIvTFNMaW8KW3vy2c0iWjiJYYAVMG6k0O1nvF5hFBbj
            VmSbzaiu3KRK0qCn1zwJacugqp2qk4Yy9jf0j2HcAzdub1OUue/RXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T12:47:47Z"
    mac: ENC[AES256_GCM,data:vL48h6SCqO003WRJip+6jPZnqT14GDVaE7CATtVDNiY3hO08/vLyo5qFwaccS9+ZfKO2+ot+LaADx/cuiIlRTFJg0VVAIz61p3BdlnbwU1rS44hZJDFS3BjTKQuRlFEt1ijodxhN1U+8FwGwh/X0h0r6xXYy1Kd9kBjj1GUidvU=,iv:WKXdGOja4h6y9kU+IyLsESWqOp+JNhHBalFTKpx1fmA=,tag:4wRatyEXPC383ta/i0FIvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
