apiVersion: v1
kind: Secret
metadata:
    name: gitlab-smtp
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:LVMA1B9MPGicTRY+OQeMnErnRKHzRg==,iv:qwDwSm/4N17EKLtx2h14yeUP+eGVUhwZZceTtTJgUIM=,tag:DIxT4SyWqAID+HRXY3heKA==,type:str]
    username: ENC[AES256_GCM,data:WRnpwcVWIBdlWUZLNWdb6gUATFc=,iv:AUKeNSDyh9pjjFz2EdqpJ3vXTbSvnoCEtUIQAgYydA4=,tag:zpAR8vImWb2iE85BqitCRw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMzJ1aEpseGt0S3I3M3Nt
            ZU80ZVc2Sy9CUWF0M0hiT2htQzBvU3pZYlJZCjA3UHZERE1GSGJXMGRac0s5d0c1
            SjJyZS9OWEx5UndibHZRMVZNSWpQMVkKLS0tIGN3K252NHcrNnZSTU1wYXZCZEJu
            QTc5V0VZbm51bVRWem8yTkI3RENLNFkKZPLltJYstB09heDP3qj/+EQaRso62ToN
            X/MnUNWW5WhAKyW3TcEAHc6g99HQ/KaTEYv7RYt10ihFQadSJWxFJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:22:20Z"
    mac: ENC[AES256_GCM,data:oPFcuUW6l4B7zBjAzcYC4VAQ9oqcPTSK0HspZKnp3HkckePVfzjYfAeXfxDZ+LkEc+YwvpglGXMHL2zfSKBahrneE3F02mpnwOz8wERGSDOFuMiQBlg8OfkrhgGxsY576DBhDGE2YKWhVu66pDH9JqUJtZin7YR2lEMDJ0ICHfY=,iv:pFvmkFQyC7y9t4gi0Jmri/XmxcdCJY//RT//KtskLE4=,tag:hnek3jdAHgRNrWLZfgJJng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
