# SPDX-FileCopyrightText: Hadi Cherkaoui <contact@hide.cherkaoui.ch>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: Namespace
metadata:
  name: moodle-mcp
  labels:
    name: moodle-mcp
    app.kubernetes.io/part-of: moodle-mcp
