apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media
  - paperless
  - websites
  - craftycontroller
  - gitlab
  - scolx
  - searxng
  - immich
  - authentik
  - matrix
  - nextcloud
  - sonarqube
