# SPDX-FileCopyrightText: Hadi Cherkaoui <contact@hide.cherkaoui.ch>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media
  - paperless
  - websites
  - gitlab
  - immich
  - authentik
  - matrix
  - ntfy
  - uptime-kuma
  - headscale
  - changedetection
  - wallos
  - anvil
  - atelier
  - filebrowser
  - moodle-mcp
  - backseat
