apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media
  - paperless
  - websites
  - gitlab
  - searxng
  - immich
  - authentik
  - matrix
  - sonarqube
  - ntfy
  - uptime-kuma
  - headscale
  - changedetection
  - wallos
  - anvil
  - atelier
  - filebrowser
