apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
  namespace: matrix
spec:
  interval: 10m
  chart:
    spec:
      chart: matrix-stack
      version: 25.12.1
      sourceRef:
        kind: HelmRepository
        name: ess-helm
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    serverName: matrix.cherkaoui.ch
    labels:
      app.kubernetes.io/part-of: matrix
    ingress:
      enabled: false
    synapse:
      enabled: true

      ingress:
        enabled: false
        host: matrix.cherkaoui.ch
      config:
        server_name: matrix.cherkaoui.ch
        public_baseurl: https://matrix.cherkaoui.ch
        federation_domain_whitelist: []
        enable_registration: true
        enable_registration_without_verification: false
        registrations_require_3pid:
          - email
        email_validation:
          enabled: true
        enable_password_auth: true
        password_config:
          enabled: true
        max_upload_size: 100M
        media_retention:
          remote_media_lifetime: 90d
        rc_message:
          per_second: 10
          burst_count: 50
        enable_metrics: true
        presence:
          enabled: true
        experimental_features:
          msc3575_enabled: true
          msc4186_enabled: true
      additional:
        1-enhanced-features:
          config: |
            turn_uris: []
            turn_shared_secret: ""
            turn_user_lifetime: 86400000
            turn_allow_guests: true

            url_preview_enabled: true
            url_preview_ip_range_blacklist:
              - '127.0.0.0/8'
              - '10.0.0.0/8'
              - '172.16.0.0/12'
              - '192.168.0.0/16'
              - '100.64.0.0/10'
              - '169.254.0.0/16'
              - '::1/128'
              - 'fe80::/64'
              - 'fc00::/7'

            # Email configuration
            # SMTP credentials will be injected via valuesFrom
            email:
              smtp_host: "proton-bridge-protonmail-bridge.gitlab.svc.cluster.local"
              smtp_port: 25
              # smtp_user and smtp_pass injected via valuesFrom below
              require_transport_security: false  # Local Proton Bridge
              notif_from: "Matrix <noreply@cherkaoui.ch>"
              app_name: "Cherkaoui Matrix"
              enable_notifs: true
              client_base_url: "https://element.cherkaoui.ch"

            enable_search: true

            admin_contact: "mailto:admin@cherkaoui.ch"

            report_stats: false
      persistence:
        enabled: true
        size: 100Gi
    matrixAuthenticationService:
      enabled: true

      ingress:
        enabled: false
        host: auth.cherkaoui.ch
      config:
        email:
          from: "auth@cherkaoui.ch"
          reply_to: "noreply@cherkaoui.ch"

        branding:
          service_name: "Cherkaoui Matrix"
        passwords:
          enabled: true
          min_length: 12
        account:
          email_change_allowed: true
          display_name_change_allowed: true
    matrixRTC:
      enabled: true

      ingress:
        enabled: false
        host: rtc.cherkaoui.ch
      sfu:
        useStunToDiscoverPublicIP: false
        manualIP: "178.82.120.243"
        additional:
          rtc:
            port_range_start: 50000
            port_range_end: 60000
            use_external_ip: true
          webrtc:
            ice_servers:
              - urls:
                - stun:stun.l.google.com:19302
                - stun:stun1.l.google.com:19302
          logging:
            level: info
          rtc_config:
            enable_simulcast: true
            video_codec: vp9
            audio_codec: opus
            opus_max_bandwidth: fullband
            opus_dtx: true
            opus_fec: true
          room:
            max_participants: 50
            empty_timeout: 300
          network:
            max_bitrate: 5000000
            min_bitrate: 100000
      service:
        type: LoadBalancer
        ports:
          http:
            port: 7880
            targetPort: 7880
          rtc-tcp:
            port: 7881
            targetPort: 7881
            protocol: TCP
          rtc-udp:
            port: 7882
            targetPort: 7882
            protocol: UDP
    elementWeb:
      enabled: true

      ingress:
        enabled: false
        host: element.cherkaoui.ch
      config:
        default_server_config:
          m.homeserver:
            base_url: https://matrix.cherkaoui.ch
            server_name: matrix.cherkaoui.ch
          m.identity_server:
            base_url: https://vector.im
        brand: "Cherkaoui Matrix"
        features:
          feature_video_rooms: true
          feature_element_call_video_rooms: true
          feature_group_calls: true
        default_theme: "dark"
        permalink_prefix: "https://element.cherkaoui.ch"
        jitsi:
          preferred_domain: meet.jit.si
        show_labs_settings: true
      additional:
        extra-config.json: |
          {
            "setting_defaults": {
              "custom_themes": [],
              "FTUE.userOnboardingButton": false
            },
            "features": {
              "feature_video_rooms": true,
              "feature_element_call_video_rooms": true,
              "feature_group_calls": true,
              "feature_native_sliding_sync": true
            }
          }
    wellKnownDelegation:
      enabled: true

      ingress:
        enabled: false
        host: cherkaoui.ch

      # Additional well-known configuration
      additional:
        server: |
          {
            "m.server": "matrix.cherkaoui.ch:443"
          }
        client: |
          {
            "m.homeserver": {
              "base_url": "https://matrix.cherkaoui.ch"
            },
            "m.identity_server": {
              "base_url": "https://vector.im"
            },
            "org.matrix.msc3575.proxy": {
              "url": "https://matrix.cherkaoui.ch"
            },
            "io.element.e2ee": {
              "default": true,
              "secure_backup_required": false,
              "secure_backup_setup_methods": ["key", "passphrase"]
            },
            "io.element.call": {
              "rtc_backend": "https://rtc.cherkaoui.ch"
            }
          }
    postgres:
      enabled: true
      persistence:
        size: 50Gi

  valuesFrom:
    - kind: ConfigMap
      name: matrix-rtc-config
      valuesKey: public-ip
      targetPath: matrixRTC.sfu.manualIP
      optional: true
    - kind: Secret
      name: matrix-smtp
      valuesKey: username
      targetPath: synapse.additional.1-enhanced-features.config.email.smtp_user
      optional: false
    - kind: Secret
      name: matrix-smtp
      valuesKey: password
      targetPath: synapse.additional.1-enhanced-features.config.email.smtp_pass
      optional: false
