apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
  namespace: matrix
spec:
  interval: 10m
  chart:
    spec:
      chart: matrix-stack
      version: 25.12.1
      sourceRef:
        kind: HelmRepository
        name: ess-helm
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    serverName: matrix.cherkaoui.ch
    labels:
      app.kubernetes.io/part-of: matrix

    synapse:
      enabled: true
      ingress:
        host: matrix.cherkaoui.ch
        tlsEnabled: false
      media:
        storage:
          size: 100Gi
        maxUploadSize: 100M
      additional:
        1-base-config:
          config: |
            public_baseurl: https://matrix.cherkaoui.ch
            presence:
              enabled: true
            enable_metrics: true
            report_stats: false
            suppress_key_server_warning: true
            trusted_key_servers:
              - server_name: "matrix.org"
            admin_contact: "mailto:admin@cherkaoui.ch"
            enable_search: true
            url_preview_enabled: true
            url_preview_ip_range_blacklist:
              - '127.0.0.0/8'
              - '10.0.0.0/8'
              - '172.16.0.0/12'
              - '192.168.0.0/16'
              - '100.64.0.0/10'
              - '169.254.0.0/16'
              - '::1/128'
              - 'fe80::/64'
              - 'fc00::/7'
            rc_message:
              per_second: 10
              burst_count: 50
            experimental_features:
              msc3575_enabled: true
              msc4186_enabled: true
        2-email-config:
          configSecret: matrix-synapse-email
          configSecretKey: email.yaml

    matrixAuthenticationService:
      enabled: true
      ingress:
        host: auth.cherkaoui.ch
        tlsEnabled: false
      additional:
        1-mas-config:
          config: |
            branding:
              service_name: "Cherkaoui Matrix"
            passwords:
              enabled: true
              minimum_length: 12
            account:
              email_change_allowed: true
              displayname_change_allowed: true

    matrixRTC:
      enabled: true
      ingress:
        host: rtc.cherkaoui.ch
        tlsEnabled: false
      sfu:
        useStunToDiscoverPublicIP: false
        manualIP: "178.82.120.243"

    elementAdmin:
      enabled: true
      ingress:
        host: admin.cherkaoui.ch
        tlsEnabled: false

    elementWeb:
      enabled: true
      ingress:
        host: element.cherkaoui.ch
        tlsEnabled: false
      additional:
        extra-config.json: |
          {
            "brand": "Cherkaoui Matrix",
            "default_theme": "dark",
            "show_labs_settings": true,
            "default_server_config": {
              "m.homeserver": {
                "base_url": "https://matrix.cherkaoui.ch",
                "server_name": "matrix.cherkaoui.ch"
              },
              "m.identity_server": {
                "base_url": "https://vector.im"
              }
            },
            "features": {
              "feature_video_rooms": true,
              "feature_element_call_video_rooms": true,
              "feature_group_calls": true,
              "feature_native_sliding_sync": true
            },
            "setting_defaults": {
              "FTUE.userOnboardingButton": false
            },
            "jitsi": {
              "preferred_domain": "meet.jit.si"
            },
            "permalink_prefix": "https://element.cherkaoui.ch"
          }

    wellKnownDelegation:
      enabled: true
      ingress:
        tlsEnabled: false
      additional:
        server: |
          {
            "m.server": "matrix.cherkaoui.ch:443"
          }
        client: |
          {
            "m.homeserver": {
              "base_url": "https://matrix.cherkaoui.ch"
            },
            "m.identity_server": {
              "base_url": "https://vector.im"
            },
            "org.matrix.msc3575.proxy": {
              "url": "https://matrix.cherkaoui.ch"
            },
            "io.element.e2ee": {
              "default": true,
              "secure_backup_required": false,
              "secure_backup_setup_methods": ["key", "passphrase"]
            },
            "io.element.call": {
              "rtc_backend": "https://rtc.cherkaoui.ch"
            }
          }

    postgres:
      enabled: true
      storage:
        size: 50Gi
