apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 10m
  chart:
    spec:
      chart: wg-easy
      version: 18.11.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: false
  values:
    persistence:
      config:
        enabled: true
        mountPath: /etc/wireguard
        size: 1Gi
    workload:
      main:
        podSpec:
          hostNetwork: false
          containers:
            main:
              securityContext:
                capabilities:
                  add: ["NET_ADMIN", "SYS_MODULE"]
              env:
                PORT: 51821
                HOST: "0.0.0.0"
                INSECURE: true
    service:
      main:
        enabled: true
        primary: true
        type: LoadBalancer
        ports:
          main:
            enabled: true
            primary: true
            port: 51821
            targetPort: 51821
            protocol: http
          wireguard:
            enabled: true
            port: 51820
            targetPort: 51820
            protocol: udp
