apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-laura
  namespace: websites
spec:
  interval: 10m
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: false
  values:
    extraVolumeMounts:
      - name: website
        mountPath: /app
        subPath: laura
    extraVolumes:
      - name: website
        persistentVolumeClaim:
          claimName: websites
    tls:
      enabled: false
    service:
      type: ClusterIP
