# IngressRoute for cherkaoui.ch homepage
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cherkaoui-homepage
  namespace: websites
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cherkaoui.ch`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        - name: cherkaoui-homepage
          port: 3000
  tls:
    certResolver: letsencrypt
