apiVersion: v1
kind: Secret
metadata:
    name: paperless-authentik
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:K+shHU9XA8WrvN5SH2BL44wp5F0GRJ5cTOv0LwNA0o33yWRRUB75Ax9cqWdjzQ/wiKUlNcrJKtHRTU850LAErcBQQO1sCYKHe+g1spTY/W8X7QVUi5m+OFxqGxm6KVsWCijbOWlOVo2Vzkai6CchxKhOlyGi57+s0DZyqLMN7RTUaX9aNWNGVdDirEUoEv6t5E/TwuZzByFc/ycGw2pOyTOHR/NnyvhyzXQrbCWTbJ1G06oAWQphJf1dsY5K9Ia2YpVzKC0yTSM8IOsZN7u3CQJJn4Y/6erYuVxptTx2H3gICi7a/CyHK1zZdR0/tbbWlo2GGFLX01tF2RPJJGvlPUpXdi9UKZ+BUKsT1eQRy8hNpezPYpoZn8QiZZVQqPOfTt+L6RsvWhg5k9Vsjykp46Z0BXwV9wBDIjmaPTEr3EhzsGJ/eU4PxDuWeg0beGO3eRSFivK+NMmERrw+LOJ7RpwzVdlZ4UI2jhz6IvWnrg+0yBXhqt+wYZV6DKHSAOocUGZZcjkhjiZrFWgVvIzpRAV7nusbzNMmUvH1JzNEiVYiwVXC6XgR+vV7FeMd5YhmyCk4Ota7iIJGSc2EAwvDeVcbQtuhwgbS+iTbhoY/JL//uFJQhupv6uNU3ByY2A==,iv:Dqj46q9SxfkXVewyc3WhBLTcobT30aUa8lZYi85wZz4=,tag:OT3qJ3xCnRSiO+DtpayWgw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVFh4Qk5IaFNnbGZQQ2V5
            czdiTzhYQmJ1VVl6dU5TbDhOTUJzWHk2VkdVClRCNFFNTi9DQnJDaWh0UG9WSjlB
            OFN1dU5XWlB3M1dMTmJOM3pqdW4vOHcKLS0tIG95SjZlQmswYSs2bmp2RGM0aUFL
            YUdQTlVFQjQzVjMxM1VPdlB5UXhDOFEKoYy9Gp/I40qJqEPDvIdFvw9U6m8P2DyH
            Ue4jwL4c1znH920aVsy7dr/f7CdhBY6cOWcOmZPScFN1/1P98KkAsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T14:22:50Z"
    mac: ENC[AES256_GCM,data:exwQLfQ7M+/Hy0bVxFyTZuIu4JPJO3H5imO/DLtwZBdjNj70pHY4JZaqWYOdp8omIlMt6ychvolbu+2hd2QTOT4AoCJTng3Zl1sGR7g/7fHt7xUAFmaWqyc4QoXYVKLxU0RPjtyt4kgxo7DFraueEY/i3dPk5Sqodo6Mukv3jU4=,iv:ma29t4vd1tNnfYR6RRvGVou9ecZByR1smvtTSLoXRL0=,tag:UCVwi3qBuWRsdxcmxbNtUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
