apiVersion: v1
kind: Secret
metadata:
    name: minio-root-credentials
    namespace: scolx
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:20jMYSw=,iv:w3k/vQiUgWHgDF/qQIQ7LlpxdpZmbLqWQ96pDEkwOIQ=,tag:EUMjY6fZGOv+aT+aPfm9ew==,type:str]
    rootPassword: ENC[AES256_GCM,data:ftoLaQg5sjZCl2RHDYxF9X7ouJpV4+ByWnG7WbnRRBYFeUAA/eCGxsN8NbASUAP/knpQWegkjIrlFspQtCqshg==,iv:V2DNP9+15qKn2LZ/F/+UN2QvthDtz91EVoDFhe3PuQM=,tag:WFBY2tW10BzJEEd1qXzjCg==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZlhvdDZrMXg5OXRSMjNw
            UTZ0MlY0MDlDMmRFaFVTZElDMFFXclYwTVgwClVjaUl1aitWUjRQcjd3VkR4OHZL
            MVB5Q1dKWFhDRXR6aUZ6NXBzQU5HM2cKLS0tIEhhaUNCTjJLWGJ2VU9FRE5FMzR0
            ZmdoMS9UOXRha29SQXJpOVVuSWR1VjgKoRzTsyoigiE0HjldXcjSqkX66xF9Ug5t
            WatliOhbeOl0bdReyCHeoAoBVkMSRS5hLlxDGcPzi3cht3DtE4BzXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T11:29:10Z"
    mac: ENC[AES256_GCM,data:a9sn2QxWOdg1f6FZcxH/71sKvbl/wyh+LRiRwvMSioXI4HevoltqiQcCu2IUc+60H6pbMxlaLyNDjb73f3Cxkqj2HiqDcnw3YnxFiQBFXdhQRp10bwBGWm7UPgMR5JQVfsqlyOo3msv2K6p49j1KSfdejsDxY51EVrqObVmZHrY=,iv:8dulRZqveCdh7s4JxYnrd10IM/oZKGjcGv408wsw1Qw=,tag:+LbuZCJylzqDuBq6CFuRHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
