apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: scolx
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:NKvVUkk=,iv:+FsDRwihGMDqjney3IhqZM0FNJzfLstTWgH5Lz6VsU4=,tag:WR8JwPsBTW+3iOTuLR662A==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:wk3f9AxZXjPq1XBOz21EF57Phwf+udVTx4+xIm9JTDjI3phaytth6KvbT26F5dm8yhjgnedm6I04fM3e8uvjlw==,iv:jTIkTABmwRYECwa7VM3eSL8seaGXYMXmIG+7TEducIY=,tag:Pttn6cDI8nseaN8pTdGTuw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRU5DSU5UK29jOE5wdTZQ
            M3VsYVdlMXEveS8rNjRnRXMvY3NVaXVuZFE4CisrcGw5T3dBRGV4c3FsMWJXN2Ro
            TTllR2J6UWl0WStlUXk3NkVrNUtGa3MKLS0tIEZ0TlFaN0E3bHB1eVNudkp4WHFP
            RE5lemtmclIycEtSVUtWZGFKLzR6dXMKKhjqIjMG/KfC5xMZ4GUY5miEjcMMjLBV
            M0/gx3MW1t2V+vfNjsx2uRc3EgcsB8/hyyjjFUG+f3pcHlF4e84ncQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T09:27:17Z"
    mac: ENC[AES256_GCM,data:j3+hwFilCmO5uJ+eGZ+GBMFwmnA/2EGu8voyhwoPNP1n1tlhViXD64t8639kL05GEgDbT+UuigVAiXGZILDj0lWQRl11QsKa5FdP/ZwXW9dDMQIixkfwlM9L0j/jTGlLqEcgRSQDtOER3PI2Skpr7t+aHYqHi5uxe2rmUP5o0yg=,iv:19fZ+x0oWLMv0f7/g83u9eQfMBG2g5H88UTmobUyGG4=,tag:L9DXtc2W0ipkOiyzxg2W0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
