apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Vmw+6BHVEd3Mbp5hqVJsfNRH+Ji8SY6SrpK+wcDahNT8oaHUFFzywHitykFb1yoT0m8NXubUk5fKJB/UTb8wK8cdkpciic8y8PgVnPMZL4HnNtQWPKfnzfVmU7p25O6iKpvNMoLB76QRJD10UoMuzfJbBWmkwW86d2nHdOrNRiQ6SBad50Yj/eQ0BTV47j3NjagbViz4a2SSfdpK7bTDyzNxtJQkVJD48J28JWlTj1IsITq4AykNv89KH6+dGhKcUx8DqitCLV8=,iv:W2XavcwMhe4qPs+Sxr2spNi6+p7YlOZY5rR1G9I+Xds=,tag:/IceAMwFh1Uz3cPVpzcPmA==,type:str]
kind: Secret
metadata:
    name: scolx-registry
    namespace: scolx
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT0dZd0ZPMEhyMENjdFRm
            WDhmbi90YkR0QUFDbHlJbm5YYVJPNXNJYUYwCk9TVnZnSkxEeXVPN2pZVXVkQitP
            SzZDZFdaMlpYeU54VVB2YnhPOHZVK2sKLS0tIFFDbjJBUTM3OEQvK1NlUzRSQnFH
            WkFGL2V5d1p6bVlQTmZidE11VURMdlEK8B/52ZG++uFqibUVUXb5uVO8E3XtfQIR
            VEeicOOf4I8W8ZlbIh1SxHPw0F4lerE3l0jv/1gMyP6Bji2PgBgdlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:07:25Z"
    mac: ENC[AES256_GCM,data:YA0NWVIPKsBmUQ/O9QplqNRZxsbRPkPROXDlN20reosJAHL3j0yKPPp7A+d9/mW04mMOibTbMsC7PxvKqjhqImm+npfPP0u9aSGeJzbEtiVT8eAA/YHgCHbl+21mb8byDQJNLuNfMEdsTWZdQW+7vnt8ReEm456sdkbQ7Z3rj5U=,iv:P/mzO/IW97N8Qt94ktucFifZBW81X966eJqCJYdLVZo=,tag:0a1B77ELZkpEEChyUuPcbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
