apiVersion: v1
kind: Secret
metadata:
    name: scolx-server-env
    namespace: scolx
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:V5wWy+whnxDIjxEQXNjuIMLR89tP+Xqru87TpteeOE5uxslVcNqiBNycmyuT/6dTlv27TXSGId8nUmWJIpuC5g==,iv:ERlqSJzGq3S1lTEXElVy0ln8+vmfB5vgaKc9xdQ0HBY=,tag:NqZtP/PQs9K+ZjSAmblR+Q==,type:str]
    JWT_ISSUER: ENC[AES256_GCM,data:exNWlgrbrBNe,iv:yCuy8veunzML6vKgZjC99VwbeiF/jU+BZbXQte42/wE=,tag:VbqeEpQ6fy9hCkbJSqEvrA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:qS1g3PuXXjq/3igeM2Doy5+Lk75YD920G2WrcIXim/45+py/mQuOmlo7GRdZHSFPJNRjlaY4dZ4fOHBX2A9CjA==,iv:u1HMk6UgM/ZlFIYiXH6btRFVrkDmoK6Oo9dgQniYYYQ=,tag:WSpJyneRHwQRbrXRwtP5dA==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:AYdarqcsF1OHPjnkhuw=,iv:DKKoRHa4A4OM1Yqc3hOsQZcrM9kpzSreubmBayVGVf0=,tag:p4iK19NZeUB1UgqVUPxvvA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:hVZ3uQoxcKxUBery0HH22yMQCBQ=,iv:Jiz1gDqgl1j4DO72hbyLgmUKPvUiBYmahv07HTnY180=,tag:Lb6osw+MonVoMhf6GuFjNw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:D2cxEmfIciaQ02CIYZ++uRBIGvlqVA==,iv:sn41Ool53EJTg2emVTxnU7AmrzEESdRMWJFzFnNSGGU=,tag:SL03nFj5Q0HCIfhgfnGX+A==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:HoODZLmFtNjNhIn6LppSda3BvH4=,iv:K+CKJkIFrZg//d77aUGZ3TYuR8U7HsyO+z0iAYtN4NQ=,tag:6jW6VHj9kGr3kSkICIuSoA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:zRkNu6n89JB6owd99cHSgHNDdOMey8JBI6BavsxsUpZNdvHOH2M=,iv:0DeCSPXlhPwenIvBemxX7XAXY5z60Drgl3OWB6EA5bg=,tag:g2wjtgjcW1fBti1zBxvlgw==,type:str]
    SMTP_TLS_SKIP_VERIFY: ENC[AES256_GCM,data:/fCZOg==,iv:kRdnnmtbf3utHupyuaoAdPg3HN99OaML9tfJklhZIo4=,tag:ugInQNsmu8DAcK4j84Z1AA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:0IQ=,iv:Hcz5Y3wg/JItb4psgueSDGWJL8HYNnMm4/xcZ1cRbVw=,tag:Qki0xPdyKwf8uswA5U098w==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:db02I0ioqARxxhwMD3/XKsQMi+PFnUp5vfehaw==,iv:BaAvl1Sb5/NZywraRHAay3e5pDrKa8VU/RnjjWckzXw=,tag:YkXtkBONdZSEIucXWV9XuQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Zul1kawxONDgA6EP5oqOCJCPXPvS89klqD7Yu3mdzuTP1hEESJVoOVeZqJxGnJZRm32e0O9UyzFYcxLhCtkShv36wHLPbffHBQ==,iv:UiQzR8VWgHZvvLEMDvnKW8SC0DfFXMEFxRzaAM8GizM=,tag:QYh0dtpjApRGZGKIZejTQQ==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:mRPTtNA=,iv:FFmc1yiNHy8yD8wOAuPC0QB7knxCt3R/pOSmWEGCz+U=,tag:HQSswTsMoZZJOqRB9C2JZA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:i4+CwuAUURw7Nb+r6EAKKSArEShhPS0HRoHTjCdq+BH6nN/j59p/CHDUg1srvv1SVK+bkesFAA0gbb4Ywyh9kQ==,iv:4lc3iEVShs6NG1lJ/fdNZaSNvVmYf9E7Blh1Zpk7WBE=,tag:U5AsnEpuLA4ZeR+H7l6BPQ==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:SsOdz7imVPE6W3+ZZIe1cGn//0clGFFNabq6+qyIBki0TVsKRyrt6JOn/68pSIPJGzKNEvh3iDd6Y3zQQjqieH6BKr/uQ2G1UZQI6TcsF0lIyto3oTfufcLPNf7vWxxxPMqreIpYXfTkG/0=,iv:e4hN/zkOaEr3CYsfn8iEE9JCpFrg+d09Ew4yEF+2OHs=,tag:Hg4Wo02K+glnzb6rZ4nwpw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:d6ZqAw2T6GRg3umuNJVynmagcAkXp/rcLwOG0hZUxEp/CiZoFW0=,iv:UBtZcd8YrKFWcS9x0fSriEGhAcreP3qT2erbAPfB28U=,tag:qo1urpPyoWi7ugi7QVJIkw==,type:str]
    STRIPE_PLUS_MONTHLY_PRICE_ID: ENC[AES256_GCM,data:da9OIj4HRRcq8f53M70fecthsYXPHW5S6HmKPaWy,iv:cCAHkyuZFHvX9CkqD8dgBWu9lEGhntuoJEhSRnFcHhc=,tag:b3vcBfVT/72DmtrFXoc9Jg==,type:str]
    STRIPE_PLUS_YEARLY_PRICE_ID: ENC[AES256_GCM,data:DNaWSbwDstfyTsP8AtDV8mJH/ONDXSic2wuJQgxm,iv:8UIpf6qmJFO7T19ZSiW96AyDjFPyN2vJCyhk+O9E0GQ=,tag:VjqubFCNdJZ/8C4wrVyRtA==,type:str]
    STRIPE_PRO_MONTHLY_PRICE_ID: ENC[AES256_GCM,data:ebgYjWz2oXfmYuXGcu26FF0Xvq9r5zeA6Q501Vou,iv:cKE+w9tc3L4dWm2PmHL3302/507i58EQKMLup5gl3Co=,tag:vJISLf24/zUPjqcABs3zvw==,type:str]
    STRIPE_PRO_YEARLY_PRICE_ID: ENC[AES256_GCM,data:ByCOotZnyaq42fobNzBGJ5JeETp29eFBGMLIci5Y,iv:qP7jDUEvTw1c3e9KY41hqebCjWwiXdQKIZq92ehBcgA=,tag:q0uUcIMCGNIAsOBa9yPFgQ==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbTdHUEpiZWxHcU9PYWpW
            eTNKelVnb1UrWkZCODltdFBhMjRYVWh1VlJZCjhqV0dKeVZ4RnhtZmcxck9vUWpY
            T3luRGk2ek1vWlVtOGJsZjVXQXRWaFEKLS0tIG5WWVRLQXl2OFRFMWs2b0lkaUll
            b3lDYlkxTmYrWWxEeHdJcm5QbzNwNEEKbmHOEVLAEtb7QERGHo1JZgevkmKFNxCt
            UD/m9YsRDSS0kZ5U3uQnmcU3pOz7Pz3lx98vYkdIW2aqKb/ZEpZTfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T09:24:11Z"
    mac: ENC[AES256_GCM,data:s/qL1CSzWKwmm4CK2Q6iCI/lUy1DBgMP9r9EcX+Bl6mXMJSTxT2ekzhVhYiVpz35mwyUZSmEEmILMBlZvv8zai5U+gYSNRW2vIzFKxkQNJntSX1o2HwCrjQP4VtNdLKC6X9BKPoLlz+9p8PbrkbIjK6uOr7uOnnlBYrbAx3UWGU=,iv:v+gAwNVPociMRfQRy0zNVR6XL87zWgsitSYJqhHnqfU=,tag:Vmjz0bmB4Y/siicHNwaHfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
