apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FeAoH/YHeR4uqJfQRjd/q+EVy3qUEDScjG53jABmGGZeYX99lmzcTdKeDIxswSLuwxWA5HP41CYKLmA+e9Jo7a5OZPqEW2ONwpdFicaWRMVFlr3iU27rMrFIC4ZUeB78LM7k3/SibKIlUNOaXCiwARg5ffYVmhgXw/Dc8XPmrVBX41ijfRuSHh6ACCxAUpSrQv0NbBMdFPL4h4ZU4Gd+V6mv7KcrxBs7O/uyBeoZPYZzY17it6kgP4N86pgNiMFoKVEV9h9C5Bg=,iv:WB1pAWPnjPCt2slekLJRVlTx1psvyApCz5lNVL1q2xE=,tag:WgfTonYvfnPu6ASjGN6nrQ==,type:str]
kind: Secret
metadata:
    name: scolx-registry
    namespace: scolx
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQUpCOW1nWWpqRkIzN2Ex
            bThIVHFSbWwrS2xMWit4V3FPMlNaVnF4RUNJCmc2LzN0WHBZK1d3SWdRTFZPSVNm
            eFpFY1VreER6b1E1REg1NHRkanRSOEkKLS0tIHBMNUttYVhSUlhDdHpBR1dPQ1o2
            U01Hd09JTHVXQ1FvaW9MN0tWU0tKVlUKaBhb/KdtI0Ee/BiqSTrCnu7zKmf5kcr+
            pHQ+UIuq24ZNqZ9Zx2WK9swJg8WJ4Ug0Jb5Zhjzp40/ArLuRwrZTJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T09:30:50Z"
    mac: ENC[AES256_GCM,data:5ZFDPtEQnYkLMXaP+y0wVFLYLqlFFQuALzbNGG5f6UQbOtyTn5N1Wiwe/vUj6yx0XEAmBcYxdGaNgQpZbFZOZ+LzaU0Wmg8+2cNEo3nRWlq1sT/ecVGa7LPCNMAWp2Ar3ej72rZ5Ybj2enneoH9t91CfiZ0i8xNeiiw/P8j4UYQ=,iv:Rdzh21K1pqFVni24X6uzz1/QJUm1bsgTq+1apn3WUso=,tag:sKJDEJIfxpRsQCsyk8ng9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
